### PR TITLE
[Issue #1809] || Allow 'enter' on keyboard for saving input on browser edit screen

### PR DESCRIPTION
**Pull request by devndevs**
## Description of the Original Issue
As detailed in [Issue #1809](https://github.com/tijlleenders/ZinZen/issues/1809), the problem appears to be related to the budget variation of the goal feature in our application. Specifically, the issue involves the inability to save and close the budget modal when pressing the Enter key, particularly when using a desktop browser.

While the original issue did not explicitly specify that the problem was confined to the budget variation, my investigation led me to this conclusion, and the implemented solution is focused on addressing this aspect.

## Implemented Solution
To resolve this, I wrapped the contents of the modal in a form that allowed me to reduce redundancy by utilizing onSubmit to allow the goal to be saved by using enter.

### CODE REVIEW

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Wow that's an excellent PR description @devndevs !

About the code:  
Can't we just remove the 'if Goal/Budget and go straight to `await handleSave()` on Enter?

**Review by Tushar-4781 — CHANGES_REQUESTED** [review]
hi @devndevs we are planning to implement form so that it auto captures the submission. via on submit. do you think you can wrap this component in form. it will save repeating LOC for us. for example "e.preventDefault(); await handleSave()"

**Comment by devndevs** [comment]
> hi @devndevs we are planning to implement form so that it auto captures the submission. via on submit. do you think you can wrap this component in form. it will save repeating LOC for us. for example "e.preventDefault(); await handleSave()"

I have done what you have requested. Wrapped the contents of the modal in a form which allowed me to reduce redundancy by utilizing on submit to allow the goal to be saved on using enter.

**Review by tijlleenders — CHANGES_REQUESTED** [review]
@devndevs Thanks for all this effort!

I can confirm it's working now on Firefox and Chrome...
... except when adding a new Goal.  

When editing an existing Goal it works fine.  
Also when adding as well as editing a Budget.  

Could you maybe investigate?

**Comment by devndevs** [comment]
> @devndevs Thanks for all this effort!
> 
> I can confirm it's working now on Firefox and Chrome... ... except when adding a new Goal.
> 
> When editing an existing Goal it works fine. Also when adding as well as editing a Budget.
> 
> Could you maybe investigate?

Hi there @tijlleenders!

May I have a little more context on the issue you are seeing? I am testing it and it is working on my end.

**Review by tijlleenders — APPROVED** [review]
Sorry @devndevs it was a caching issue...

All good here, thanks for the great work!

**Review by Tushar-4781 — APPROVED** [review]
Thanks 👍

**Pull request merged**
