### PR TITLE
Solves #1187: added blog link to dropdown menu

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
Added blog link to dropdown menu. Solves issue #1187

### CODE REVIEW

**Review by tijlleenders — APPROVED** [review]
Looks good from UI side.

@Tushar-4781 maybe a switch statement is preferred here?

**Comment by Tushar-4781** [comment]
> Looks good from UI side.
> 
> @Tushar-4781 maybe a switch statement is preferred here?

if else is fine till we have less than 5 cases to check

**Review by Tushar-4781 — APPROVED** [review]
Thank you for your contribution

**Comment by Tushar-4781** [comment]
Resolves #1187

**Pull request merged**
