### PR TITLE
strikethrough done goals

### LINKED ISSUE #822: Strikethrough goal text when done - hide done when revisiting
Strikethrough when marking it done (just like on MyTime page) - so don't hide it.

After navigating away and coming back - hide it in the archived area at the bottom.  
It would be nice if the strikethrough has the color of the goal.

**Additional context**   
This issue was previously implemented, but not in the way as specified in the issue.  
The crossed out goal now remains for a number of seconds, then suddenly disappears. This is surprising, confusing and also makes the position of the Goals suddenly change, causing you frustration when you want to tap some goal, and right before you hit it, it shifts to some other goal.

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #822

### CODE REVIEW

**Review by tijlleenders — CHANGES_REQUESTED** [review]
This is not working as expected.

When I complete multiple goals, suddenly a subset of them appears in Done, even though I haven't navigated away yet:
image


When I do navigate and come back, I expect them all to be in 'Done' - without any crossed out. Instead I see this:  
image

**Review by Tushar-4781 — CHANGES_REQUESTED** [review]
Please change the implementation to jquery style. the feature is just a temporary change on UI. we don't need to use global state for this.

**Comment by vinaybadgujar102** [comment]
> Please change the implementation to jquery style. the feature is just a temporary change on UI. we don't need to use global state for this.

Please elaborate. I am not familiar with jQuery.

**Comment by Tushar-4781** [comment]
> > Please change the implementation to jquery style. the feature is just a temporary change on UI. we don't need to use global state for this.
> 
> @Tushar-4781, Please elaborate. I am not familiar with jQuery.

@vinaybadgujar102 directly manipulate the DOM instead of doing it via react state.

**Comment by vinaybadgujar102** [comment]
> This is not working as expected.
> 
> When I complete multiple goals, suddenly a subset of them appears in Done, even though I haven't navigated away yet

@tijlleenders, the subgoals location state has some bugs. It is related to location history I guess. 
https://github.com/tijlleenders/ZinZen/issues/1989#issuecomment-2264837583 It should be handled in a separate issue.

**Comment by vinaybadgujar102** [comment]
@Tushar-4781 changed the approach as suggested

**Review by Tushar-4781 — CHANGES_REQUESTED** [review]
@vinaybadgujar102 can you try directly accessing the title component by using the goal id and then using the class name goal-title. we don't the ref or prop either

**Review by tijlleenders — CHANGES_REQUESTED** [review]
@vinaybadgujar102 Please keep this as draft until it is ready to be testd again. Currently not working correctly when completing multiple goals.

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Works as expected.
Can we make the strikethough line a bit thicker?

I can hardly see breakfast is crossed out here:

**Review by tijlleenders — CHANGES_REQUESTED** [review]
You can double the thickness.

**Review by tijlleenders — APPROVED** [review]
Great, thanks!

**Comment by tijlleenders** [comment]
@Tushar-4781 Changes OK?

**Review by Tushar-4781 — APPROVED** [review]

**Pull request merged**
