### PR TITLE
App background color changed

### LINKED ISSUE #1527: Use darker background in dark mode
**Is your feature request related to a problem? Please describe.**
The background of the new theme is too light. The previous one was nicer. [Google material design recommends #121212](https://m2.material.io/design/color/dark-theme.html#properties)

**Describe the solution you'd like**
Use #121212

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by Shubham-Praj**
Resolves #1527

Below is the screenshot of app after the changes. 
Please let me know, if I miss understood something. 

image

### CODE REVIEW

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Hi @Shubham-Praj 

This is a good step - but there are two places where this doesn't work out yet.

1. Light mode


2. Dark mode MyTime screen


The more elevation, the lighter the dark background. So the header shouod be the greyest/lightest. The today/focus/thisweek in between the header grey and the darkest dark.

**Comment by Shubham-Praj** [comment]
Hey @tijlleenders got it. Sorry, my bad, missed the other screens and understanding. I will try to get this fixed

**Comment by tijlleenders** [comment]
No worries @Shubham-Praj !

That's why there's reviews right?

**Comment by Shubham-Praj** [comment]
Hii @tijlleenders yes you right. 
Here's a new PR I tried to fix UI based on the inputs provided by you.

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Thanks @Shubham-Praj 

The light theme is kind of screwed up now:  



Also Google Material Design recommends #121212 as the darkest color - not #000000

Signal has an even lighter setting. I guess it's about taste? Personally I'd go for #121212


What do you think?

**Comment by tijlleenders** [comment]
Thanks for the efforts - we'll see who can pitch in. Hopefully it'll be a learning experience. 

@vinaybadgujar102 Do ypu want to try this one?

**Review by tijlleenders — APPROVED** [review]
Thanks @Shubham-Praj and @vinaybadgujar102 !

**Pull request merged**
