### PR TITLE
Enabling Install to Desktop

### LINKED ISSUE #207: Enable install to desktop
Using Chrome a PWA should be installable to desktop.

### PR DESCRIPTION
**Pull request by Tushar-4781**
WIP!!

Resolves #207

### CODE REVIEW

**Comment by Tushar-4781** [comment]
image

Locally I m able to install and in Application Tab ( in Inspect ). I can see the service worker as well and the Lighthouse report also gives a green signal but here the deployment link does not show the same behavior.

@GithinjiHans @pulkitvyas08 @tijlleenders Can you guys have a look once.

**Comment by Tushar-4781** [comment]
ignore the last two commits. The issue is like service worker file is not included in deployment
image

**Comment by tijlleenders** [comment]
I'v had a look but no install icon appears.
Checked:
- Chrome Version 101.0.4951.67 (Official Build) (64-bit).
- Firefox 101.0 (64-bit)

**Comment by Tushar-4781** [comment]
> I'v had a look but no install icon appears. Checked:
> 
> * Chrome Version 101.0.4951.67 (Official Build) (64-bit).
> * Firefox 101.0 (64-bit)

locally they are visible
image

**Comment by tijlleenders** [comment]
Yeah, sorry. 
I mean the install icon in the Chrome/FF menu bar.

**Comment by Tushar-4781** [comment]
Checkout this commit 8c3560703b185ac4d328c898c079d7b0697bd8e6 . Till this everything is working and do run npm install and workbox cli once

**Pull request closed without merging**
