### PR TITLE
add: dynamic styling to toast based on theme 

### LINKED ISSUE #1468: Update wording patner mode
**Is your feature request related to a problem? Please describe.**
It's very nice when language is clear.

**Describe the solution you'd like**
Change current text in partner toast measage to:  
Do you have a partner?  
Try sharing a goal privately.  
Click on a goal circle to start.  

**Describe alternatives you've considered**
Keeping it the way it is. It's a litle co fusing. Not many people understand 1:1.

**Additional context**

### LINKED ISSUE #1482: Dark mode for Toast messages
**Is your feature request related to a problem? Please describe.**
It's very annoying when a big white thing show up unexpectedly in dark mode.

**Describe the solution you'd like**
A dark mode Toast.

**Describe alternatives you've considered**
None.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #1482 @tijlleenders 
resolves #1468 
Please check if the styling of the toast is according to your preference

### CODE REVIEW

**Comment by tijlleenders** [comment]
Thanks @vinaybadgujar102 !

Did you test it locally?
It would be nice if the subtext also shows 😉 
image

**Comment by vinaybadgujar102** [comment]
how to reproduce this action?

**Comment by tijlleenders** [comment]
@vinaybadgujar102 There is no action.  
I just selected the text 'actions' in my browser to make it obvious that there is black text on blavk background.  

The only thing that needs to be resolved for this issue is make the font color white so that you can see what is written. If you look closely you see there is black text.

**Comment by tijlleenders** [comment]
@vinaybadgujar102  
You could also resolve #1468 at the same time in this PR?

**Comment by vinaybadgujar102** [comment]
resolves #1468. 
@tijlleenders made request changes

**Comment by tijlleenders** [comment]
Thanks, looks good now @vinaybadgujar102 !

Will let @Tushar-4781 merge.

**Comment by tijlleenders** [comment]
@Tushar-4781 Maybe the background color should be adjusted to be a few tints lighter, as it should 'float' on top over everything?

**Review by Tushar-4781 — APPROVED** [review]
Nice

**Pull request merged**
