### PR TITLE
New Feature: Soft Delete Goal

### LINKED ISSUE #1625: Soft delete
**Is your feature request related to a problem? Please describe.**
It's very annoying when you accidentally press Delete on a Goal, especially when it contains a whole tree of things. Right now this is pretty easy to do - because the edit menu is 25% reserved for the Delete button.

**Describe the solution you'd like**
Make the Delete a soft delete. Whenever you delete something, it gets placed in the Archive for 7 days before it is actually deleted. 

**Describe alternatives you've considered**
Make the delete button smaller. This would reduce the risk, but it can still happen.

**Additional context**
No need to differentiate between the real archived goals and the soft-deleted goals. If needed we can make a separate issue for that.

### PR DESCRIPTION
**Pull request by Tushar-4781**
This PR introduce soft delete functionality which works at all levels and in sharing.
Edge Case Left - If a top (root) level goal is deleted which is colab goal then the current implementation will not give option to restore it.

Resolves #1625

### CODE REVIEW

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Please investigate the  failing tests so we can get this merged.

**Review by tijlleenders — APPROVED** [review]
Awesome!

**Comment by Tushar-4781** [comment]
@tijlleenders @vinaybadgujar102 i have zero clue how its passing the test in the PR. i ran locally still tests are failing i.e. 1 failed 4 skipped
image

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Investigate tests failing on merge.

**Pull request merged**
