### PR TITLE
Fix: title and circle alignment

### LINKED ISSUE #1412: Fixed alignment title when expanding goal
**Is your feature request related to a problem? Please describe.**
It's very annoying when alignment of the title is broken when expanding a goal.

**Describe the solution you'd like**
Always keep title aligned with middle of the goal circle.

**Describe alternatives you've considered**
None.

**Additional context**

### PR DESCRIPTION
**Pull request by Tushar-4781**
Resolves #1412

### CODE REVIEW

**Comment by tijlleenders** [comment]
Still off in DuckDuckGo and Chrome.

**Comment by tijlleenders** [comment]
The title shifts down a few pixels on expanding in Chrome

**Comment by Tushar-4781** [comment]
it was in draft when u r reviewed :D

**Comment by Tushar-4781** [comment]
its little weird at my end locally things are aligned  but in preview link its not balanced
image

**Comment by tijlleenders** [comment]
Still off on Chrome and DuckDuckGo:

**Review by tijlleenders — APPROVED** [review]
Good enough. 
We can worry about this later.

**Pull request merged**
