### PR TITLE
Explore Page

### LINKED ISSUE #288: Make the explore page
Make the page as designed in #241

Per category think of a few titles of plans that will be liated when you click on a category. They don't have to be clickable yet. It is to demo the idea to people and get feedback.

### PR DESCRIPTION
**Pull request by Tushar-4781**
Resolves #288

### CODE REVIEW

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Looks good.

Can you make an extra issue for translation and one for adding dark theme?

Two things:
- The circle is not round on my screen:

- The Add goal page is not rendering. Not sure if that's normal, and if it's only me

**Comment by Tushar-4781** [comment]
Yeah i haven't link to add goal.
Though I checked on multiple devices. Button was round. I will check again on all. Can you tell me what device u r using.

**Comment by Tushar-4781** [comment]
> Looks good.
> 
> Can you make an extra issue for translation and one for adding dark theme?
> 
> Two things:
> - The circle is not round on my screen:
> 
> - The Add goal page is not rendering. Not sure if that's normal, and if it's only me

Yeah i haven't link to add goal.
Though I checked on multiple devices. Button was round. I will check again on all. Can you tell me what device u r using.

**Review by tijlleenders — APPROVED** [review]
Add circle still 'squished' on DuckDuckGo.

Allowing to not waste time on a detail.

Nice job!

**Pull request merged**
