### PR TITLE
explain empty partner page

### LINKED ISSUE #1728: Explain empty partner page
**Is your feature request related to a problem? Please describe.**
It's very annoying when you manage to add a partner but it remains unclear if they accepted or not.

**Describe the solution you'd like**
Add some explanation on the status of the partner invitation.  

- Your partner has accepted the sharing request but has not started sharing anything with you.  
- Your partner has not accepted the sharing request yet. Click the button below to share again.  
[ share icon - Share link ] <= button. 

**Describe alternatives you've considered**
None.

**Additional context**

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #1728

### CODE REVIEW

**Review by tijlleenders — CHANGES_REQUESTED** [review]
I'm not seeing the tour.  
Also, on the receiving side, I see the 'your partner has not yet accepted the sharing request, please share again' - which is weird. If anything this should show on the sharer's side.

**Comment by vinaybadgujar102** [comment]
Hey @tijlleenders, I have updated the code. Please verify if the requested changes are implemented correctly.

**Comment by tijlleenders** [comment]
> I'm not seeing the tour to explain empty partner page on the receiving side. Also, on the receiving side, I see the 'your partner has not yet accepted the sharing request, please share again' - which is weird. If anything this should show on the sharer's side.

Thanks @vinaybadgujar102 
My comment was misinterpreting the scope the issue you are solving. The #1761 focuses on the sender side (Partner A). My comment was about the receiving side. When Partner B opens the sharing request they see this: 
image
- I'd expect it to say something like 'This is where you can see all the goals shared by [name given to A when accepting request]. At the moment there are no goals shared with you yet by [name given to A when accepting request].'

So basically the message you're showing on the sender's side is also showing identically on the receiver side - which is wrong. If you stick to the scope of the issue - you'd only see it on the sender side and show nothing on receiver side. Ideally we can fix both by expanding the scope of the issue a bit.

- The font and everything is completely out of design. Please make it conform to the way we show messages / fonts / thicknesses on other pages. I was assuming you'd use the 'Tour' component but since we're proposing a button that's indeed not appropriate.

- When the notification B has accepted comes in on sender (A) side, the screen behind the notification remains the same - saying B still needs to accept. When the notification comes in - this should show 'Your partner has accepted the sharing request but has not started sharing anything with you.'
image

**Comment by vinaybadgujar102** [comment]
should the empty partner page text be displayed every time the page is empty or only the first time?

@Tushar-4781 @tijlleenders what is the logic to differentiate sharer and receiver in the app? In this PR basically, I show content based on the contact's "accepted" value in "contactsCollection". I cant find a way to distinguish between "sharer" and "receiver".

**Comment by tijlleenders** [comment]
@vinaybadgujar102 
Good point. The empty partner page text should be displayed every time the page is empty. Just remove the 'yet' and the message is valid for the first time, and for subsequent times where things have been 'unshared' (although I'm not sure if we support that right now).

**Comment by vinaybadgujar102** [comment]
> @Tushar-4781 @tijlleenders what is the logic to differentiate sharer and receiver in a relationship? 

 I cant find a way to distinguish between "sharer" and "receiver".

**Comment by tijlleenders** [comment]
@Tushar-4781 Can you help out to get this PR moving again?

**Comment by vinaybadgujar102** [comment]
@tijlleenders, I've updated the code based on your feedback. Please review it to see if it meets the expectations?

**Review by tijlleenders — APPROVED** [review]
Great!  

We still need to refresh but that is by design for now.
This is already way better :)

**Comment by tijlleenders** [comment]
@Tushar-4781 Can you review code?

**Review by Tushar-4781 — APPROVED** [review]

**Pull request merged**
