### PR TITLE
Update: Resolving Minor issues

### LINKED ISSUE #1090: Add weekdays filter to scheduler call
The "Weekdays" filter should be passed to the scheduler.  

If I create a "Work" root goal with:
- a budget of 35h/week
- a filter on "Weekdays"
- an after-before filter of 8-16  
... the output to the scheduler should be:
```
{
  "startDate": "2023-03-09T00:00:00",
  "endDate": "2023-03-20T00:00:00",
  "goals": {
    "1": {
      "id": "1",
      "title": "work",
      "budgets": [
        {
          "budget_type": "Weekly",
          "min": 35,
          "max": 45
        }
      ],
      "filters": {
        "after_time": 8,
        "before_time": 16,
        "on_days": "Weekdays"
      }
    }
  }
}
```

I believe the on_days filter is currently not being sent.

### LINKED ISSUE #1100: Rename Feelings to Journal in header

### LINKED ISSUE #1108: Change forget sound
@Tushar-4781 
I've been using the forget and I think we need a different sound. The current one sounds like I have done something wrong...

I would like it to sound more like *swoosh* wind that blows the task away.
If you prefer I'll try finding something that fits better.

### LINKED ISSUE #1112: Don't show inbox if it's empty

### LINKED ISSUE #1113: Don't show archive if 0 archived

### LINKED ISSUE #1115: Move delete button to archive
Only offer 'Delete forever' from archive - not from regular sub-icons.

Motivation: you don't need it that often, it clutters sub-icons, and you don't want to press it by accident.

### LINKED ISSUE #1116: Make Onboarding finished when you've selected the theme and lang
Currently, the onboarding ends after query page. so, if on query user makes a decision to click on zinzen logo the onboarding is still on which means new users can't accept the invite link because the invite screen can only appear if a user is fully registered. i.e. successfully onboarded.

### PR DESCRIPTION
**Pull request by Tushar-4781**
Resolves #1116 
Resolves #1113 
Resolves #1112 
Resolves #1108 
Resolves #1100 
Resolves #1090

### CODE REVIEW

**Comment by tijlleenders** [comment]
I don't see #1115 implemented.

**Comment by Tushar-4781** [comment]
> I don't see #1115 implemented.

by mistake, need a discussion on that.

**Review by tijlleenders — APPROVED** [review]
Great!
Can we use separate PRs for unrelated issues?

**Comment by Tushar-4781** [comment]
> Great! Can we use separate PRs for unrelated issues?

cool

**Pull request merged**
