### PR TITLE
533 call the scheduler on mytime page

### PR DESCRIPTION
**Pull request by GithinjiHans**

### CODE REVIEW

**Review by tijlleenders — CHANGES_REQUESTED** [review]
My bad.
A discussion is needed before continuing on this PR. There is a discussiom somewhere with Newton and/or @pulkitvyas08 that using git submodules is not the way to go.
I should have included more information.

**Comment by GithinjiHans** [comment]
Yeah...They are not actually important right now. I can remove the submodule and It will still work.

**Comment by tijlleenders** [comment]
I was assuming you would discuss this with @sokorototo - as you see him frequently and he's doing the WASM part.
The discussion where we decide not to use submodules is in #361

**Comment by tijlleenders** [comment]
> Yeah...They are not actually important right now. I can remove the submodule and It will still work.

Sure, thanks for taking it that way :)
From #361 I deduce we don't want the wasm in /src
Not sure if the same is true for the api.ts - we should have it in one place, not in two repos.

**Comment by GithinjiHans** [comment]
Sure...we don't need the wasm because it's loaded using a URL but I think the api.ts is needed.

**Comment by GithinjiHans** [comment]
I've tried using the URL to access the api.ts and it just fails.
We can draft this PR and discuss on where to keep the api.ts ....backend or frontend?

**Comment by tijlleenders** [comment]
This PR was for trying to integrate by caloing the wasm module via the GH URL from the frontend code.

That didn't work so we'll start fresh in a new PR for the other methods discussed in #361

**Pull request closed without merging**
