### PR TITLE
Solved eslint path alias import errors

### PR DESCRIPTION
**Pull request by GithinjiHans**

### CODE REVIEW

**Comment by GithinjiHans** [comment]
Screenshot from 2022-05-29 21-23-21

**Comment by GithinjiHans** [comment]
I forgot to switch to another branch before making the resizing changes but I hope ths works too.

**Review by pulkitvyas08 — CHANGES_REQUESTED** [review]
@GithinjiHans Why is this PR deleting the images from the explore page?

**Comment by GithinjiHans** [comment]
I changed the image sizes from Mbs to Kbs for them to load faster....that solves #354.Its just that i forgot to switch to a new branch for that issue.All the images are there just resized but the quality is maintained

**Comment by pulkitvyas08** [comment]
> I changed the image sizes from Mbs to Kbs for them to load faster....that solves #354.Its just that i forgot to switch to a new branch for that issue.All the images are there just resized but the quality is maintained

Okay then. Please make sure to include the resized images in the new PR

**Review by pulkitvyas08 — APPROVED** [review]

**Pull request merged**
