### PR TITLE
Breadcrumb only shows latest level down

### LINKED ISSUE #2003: Breadcrumb only shows latest level down
**Describe the bug**
In main the breadcrumb is working. In develop branch it isn't.

**To Reproduce**

1. Go to Daily Routine, then Lunch
2. See 'Daily routine' is not in the breadcrumb

**Expected behavior**
See 2.

**Screenshots**
None.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by Nicholas-Kipkoech**
resolves #2003

### CODE REVIEW

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Making a new goal at a nested level destroys the breadcrumb.

**Comment by Nicholas-Kipkoech** [comment]
@Tushar-4781 When I add a subgoal the goals history is destroyed and the breadcrumb falls, can we use another alternative? since `useLocation` state doesn't persists data.

**Comment by Tushar-4781** [comment]
@Nicholas-Kipkoech  useLocation relies on browser state history which persists even after you refresh.

**Review by tijlleenders — APPROVED** [review]
Yup it works now!

**Pull request merged**
