### PR TITLE
add goal quicker

### LINKED ISSUE #1957: Make adding a Goal quicker
**Is your feature request related to a problem? Please describe.**
It's very annoying when you have to press twice to add a Goal.  
- First tap on '+' to see the menu 'Add Goal' and 'Add Budget'
- Then tap on 'Add Goal' 

**Describe the solution you'd like**
Immediately open the 'Add Goal' modal when tapping the '+'.
Only show the two options when you long press the '+'

**Describe alternatives you've considered**
1 A way of upgrading from a Budget to a Goal. This will be implemented later - explained in a separate issue. That will be the end state.
2 Having a switcher in the Modal. This was tried for a while but is confusing.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #1957

### CODE REVIEW

**Review by tijlleenders — CHANGES_REQUESTED** [review]
The adding works as expected, but there is something wrong with the breadcrumb when going down into the hierarchy. If that is also wrong in the develop branch, please log an issue. Otherwise please fix it in this PR.

**Comment by tijlleenders** [comment]
[Uploading Screencast from 2024-07-24 17-35-32.webm…]()

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Same question for disallowing creating a budget whenever **any ancestor** is a simple Goal with a duration.

This now only works for direct ancestors.
[Screencast from 2024-07-24 17-42-58.webm](https://github.com/user-attachments/assets/980c7916-26cf-4e14-8342-a9f8e9c7dedd)

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Please note that these things are supposed to be working in main branch, so we should look at the solution there, before developing the same thing twice.

**Comment by vinaybadgujar102** [comment]
> Same question for disallowing creating a budget whenever **any ancestor** is a simple Goal with a duration.
> 
> This now only works for direct ancestors. According to #1857 this should be working in main branch. [Screencast from 2024-07-24 17-42-58.webm](https://github.com/user-attachments/assets/980c7916-26cf-4e14-8342-a9f8e9c7dedd)

Same, the problem is in develop branch.

**Comment by tijlleenders** [comment]
@Tushar-4781 I already gave my review.

**Comment by Tushar-4781** [comment]
@vinaybadgujar102 rebase with develop branch. the breadcrumbs will be visible to you. sorry for the inconvenience

**Comment by tijlleenders** [comment]
@vinaybadgujar102 I don´t understand the extra commits. This was ready to merge, just needed a rebase.  
Are you implementing the next issue without merging?

**Comment by vinaybadgujar102** [comment]
@tijlleenders, Only one commit was added ([2ad4e3f](https://github.com/tijlleenders/ZinZen/pull/1968/commits/2ad4e3fe55ef458d364ded901b114f3c0bde187f)). It is just a small change which was missed while resolving merge conflict.

**Comment by vinaybadgujar102** [comment]
@tijlleenders, I used `git pull --rebase` command which re-commits the changes made, introducing new commit hashes. So the changes are same for each commit just hashes are new. 
There is only one new change ([94d5c18](https://github.com/tijlleenders/ZinZen/pull/1968/commits/94d5c18416e29612b0d117d7cd9d2c6a0e430844)). It is just a small code change which was missed while resolving merge conflicts.

**Comment by tijlleenders** [comment]
Thanks - I missed that!

**Review by tijlleenders — APPROVED** [review]

**Pull request merged**
