### PR TITLE
restoring from done missing

### LINKED ISSUE #1991: Restoring from done missing
**Is your feature request related to a problem? Please describe.**
It's very annoying when you want to restore from done, and it's missing.

**Describe the solution you'd like**
Implement restore from done, just like it is done in the main branch, adapt if needed:  
image

**Describe alternatives you've considered**
None.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by Nicholas-Kipkoech**
resolves #1991

### CODE REVIEW

**Comment by Nicholas-Kipkoech** [comment]
@vinaybadgujar102  Can we collaborate on this?

**Comment by Nicholas-Kipkoech** [comment]
@Tushar-4781  Can you look at this maybe you can guide on how I can tackle this.

**Comment by vinaybadgujar102** [comment]
@Nicholas-Kipkoech, could you please state the issue you are facing?

Currently, goals that are marked as "Done" and those that are deleted have the same goal actions: "Restore" and "Delete." The "Delete" action has not been implemented yet, and we have a separate issue for that.

In the develop branch, the correct options are shown for goals in the Trash, but not for goals that are marked as "Done." So, please first focus on solving the "Restore" implementation. You can find the appropriate restore function exported from the useGoalActions file.

After that, ensure the correct goal options are displayed for "Done" goals. You can use the DeletedGoals.tsx file as a reference for this.

**Comment by Nicholas-Kipkoech** [comment]
@vinaybadgujar102 Thanks! let me do the necessary

**Comment by Nicholas-Kipkoech** [comment]
@vinaybadgujar102 I have added the missing actions, I checked the DeletedGoal.tsx and I realized the provider was created for it. Do I have to create a new provider for the archived goals?

**Comment by vinaybadgujar102** [comment]
@Tushar-4781 

> @vinaybadgujar102 I have added the missing actions, I checked the DeletedGoal.tsx and I realized the provider was created for it. Do I have to create a new provider for the archived goals?

@Tushar, what do you think?

**Comment by Nicholas-Kipkoech** [comment]
@Tushar-4781 Can you check on the comment above so that I can continue.

**Comment by Tushar-4781** [comment]
@Nicholas-Kipkoech we don't need any kind of provider. we just need goal actions component to show the actions for done goals. i will add to this PR i already have them prepared. you can continue on another issue :)

**Pull request closed without merging**
