### PR TITLE
Show minutes as superscript #1141

### LINKED ISSUE #1141: Show minutes on calendar as superscript
Right now the calendar time is shown as a long blob of text which is hard to read.

Example: "0:00-08:00"

It would be better to:
- remove any leading 0's ; so 08:00 => 8:00
- move the minute portion to superscript position ; so 8:00 => 800 (where 00 is in superscript)

### PR DESCRIPTION
**Pull request by Shahzaib-Iqbal-1057**
Resolves #1141

Hey! I have changed the way the time format looks : 
-Right now, I have removed the leading zeroes and also put the minute values in superscript, but the minute values won't be looking as good I think as all minute values are zeroes currently. 
-So, I have provided some more commented code with it as well in which only the leading zeroes are removed and there is no superscript. You can take a look at it if you want to.

### CODE REVIEW

**Comment by tijlleenders** [comment]
Thanks for the effort @Shahzaib-Iqbal-1057 !

Doesn't it look better already?

It would be great if there's a way to make it pixel perfect. @Tushar-4781 any ideas?

**Comment by Shahzaib-Iqbal-1057** [comment]
Try and decrease the vertical-align property by 3-4%  :)

**Comment by Tushar-4781** [comment]
> Try and decrease the vertical-align property by 3-4% :)

go ahead. You can do this

**Comment by Shahzaib-Iqbal-1057** [comment]
Take a look now

**Comment by tijlleenders** [comment]
Perfect @Shahzaib-Iqbal-1057 , **exactly right!**

Do you need help resolving the merge conflicts?  

Also, could you align the hours with title?  
The first digit of the Tasks with two-digit starting hours should align left with the Task title.  
The time of Tasks with single-digit starting hours should align too, but with the - separator of the two-digit starting hours.  
Hope that explanation is clear... 😊

**Comment by tijlleenders** [comment]
@Shahzaib-Iqbal-1057 Are you resubmitting this in a new PR?
There was just the alignment issue left...

**Comment by tijlleenders** [comment]
@Tushar-4781 Please pick this one up. It's a shame to let the work go unmerged like this.

**Pull request closed without merging**
