### PR TITLE
add hint toggle in config modal

### LINKED ISSUE #1629: Add 'Hints' toggle to Goal and Budget edit screen
**Is your feature request related to a problem? Please describe.**
It's very nice to get hints.

**Describe the solution you'd like**
Add a (default switched off) Hints toggle to the Goal and Budget create/edit menu like so:
image

**Describe alternatives you've considered**
Integrating the text inside the toggle like so:
image

This does however create a very big area of action color on the screen. It also is less readable/accessible with font size being smaller and lower contrast. 
The alternative with 'Hints' outside of the toggle is better/cleaner/more discreet/more accessible/less noisy.

**Additional context**

Image

Image

The Hints functionality will not be complete - but this toggle is the first step.  
It later has to be connected to querying the pseudoanonymousmessages endpoint to retrieve any hints on a random weekly basis - and create a notification dot if there are new Hints, together with a Hint modal with 'Report'/'Dismiss'/'Next'/'Add'/'Snooze for a week' buttons.  
There will be separate issues for that.

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #1629

### CODE REVIEW

**Comment by tijlleenders** [comment]
Regression effect:
image

**Comment by tijlleenders** [comment]
Can you align the Hints text left?
image


Also, when not active the button should have a grey color, like so:
image

**Comment by vinaybadgujar102** [comment]
Only hint text should be aligned?

**Comment by tijlleenders** [comment]
I don't understand.  
Align all things to make it look nice.

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Thanks Vinay.

I'm not an expert on UI design - but I know this is not recognizable as a toggle:


We need a better foreground, background and outline color for dark mode.  
You can use the internet as inspiration : 



Also, I think the X is too busy/noisy.  
Could you remove it so the default off setting doesn't "shout"?  
Please leave the checkmark for now.

**Review by tijlleenders — APPROVED** [review]
We can use it like this!

@Tushar-4781 OK on code?

**Review by Tushar-4781 — APPROVED** [review]

**Pull request merged**
