### PR TITLE
refactor: remove goals border bottom

### LINKED ISSUE #1532: Remove separation between goals
**Is your feature request related to a problem? Please describe.**
It's very nice and peaceful when the UI is minimalistic and not too busy.

**Describe the solution you'd like**
Try removing the separator between goals.  
I'm not sure we'll merge it - but let's try it out in the PR and see if it works out.  
The current spacing is probably sufficient to not need the separator lines.

**Describe alternatives you've considered**
A lighter/thinner separator. We can't get much lighter/thinner than this.

**Additional context**  
Current UI with separators:

### PR DESCRIPTION
**Pull request by ftonato**
Closes #1532

### CODE REVIEW

**Comment by tijlleenders** [comment]
Thanks @ftonato - this looks promising!

Could you also remove the separator line on the MyGoals page?

**Comment by ftonato** [comment]
@tijlleenders added ;)

**Review by tijlleenders — APPROVED** [review]
Very nice @ftonato 

I like it. It a lot calmer on the eyes and still very orderly through the spacing.

Let's try it for a while. Thanks!

**Comment by ftonato** [comment]
@tijlleenders can you add the correct labels to allow your project to be part of `hacktoberfest` event?

**Pull request merged**
