### PR TITLE
fix eslint issues (WIP)

### PR DESCRIPTION
**Pull request by vinaybadgujar102**

### CODE REVIEW

**Comment by vinaybadgujar102** [comment]
@Tushar-4781 please suggest how "Dependency cycle detected." eslint issue can be solved?

**Comment by Tushar-4781** [comment]
> @Tushar-4781 please suggest how "Dependency cycle detected." eslint issue can be solved?

only one move one of the function to different module to break the cycle

**Comment by vinaybadgujar102** [comment]
@Tushar-4781, I have resolved all the linting issues but am stuck on the issues in "GoalProcessor.ts." The problem mentions deleting the indentation in the given line, but when I do it, my editor throws an error (to add indentation) . So there is a conflict between my editor and workflow. Do you have any solution of this?

**Comment by Tushar-4781** [comment]
> @Tushar-4781, I have resolved all the linting issues but am stuck on the issues in "GoalProcessor.ts." The problem mentions deleting the indentation in the given line, but when I do it, my editor throws an error (to add indentation) . So there is a conflict between my editor and workflow. Do you have any solution of this?

@vinaybadgujar102  can you post screenshot ?

**Comment by vinaybadgujar102** [comment]
@Tushar-4781 

Screenshot from 2024-03-31 19-01-14

Screenshot from 2024-03-31 19-02-08

**Comment by Tushar-4781** [comment]
> @Tushar-4781, I have resolved all the linting issues but am stuck on the issues in "GoalProcessor.ts." The problem mentions deleting the indentation in the given line, but when I do it, my editor throws an error (to add indentation) . So there is a conflict between my editor and workflow. Do you have any solution of this?

uhm not sure cuz i don't see it happening at my end. i can push this fix if u want. cuz at my end its working fine.

**Comment by vinaybadgujar102** [comment]
Ok. You can push the commit

**Review by tijlleenders — APPROVED** [review]

**Comment by tijlleenders** [comment]
Go for green!

**Pull request merged**
