### PR TITLE
Update: Switching to antd | Removed: Unwanted Deps 

### LINKED ISSUE #1163: New theme increased bundle size
**Is your feature request related to a problem? Please describe.**
I was expecting a bundle reduction with the new theme - instead it increased!

**Describe the solution you'd like**
Remove bootstrap if we're only using antd now.  
Make sure we're only rolling up the parts of bootstrap/antd that we use into the dist.
... or better even ... use a CDN for these parts so there is a chance of it being in cache of user's browser.

**Additional context**
Old build:
```
dist/assets/index.16f34166.css                                  377.79 KiB / gzip: 59.50 KiB
dist/assets/index.18d34b4b.js                                   750.03 KiB / gzip: 242.67 KiB
```
New build:
```
92 files changed, 2082 insertions(+), 21712 deletions(-)
dist/assets/index.94c445aa.css                                  228.07 KiB / gzip: 38.06 KiB
dist/assets/index.b51a1904.js                                   1071.33 KiB / gzip: 345.98 KiB
```
Build after #1215:  
```
dist/assets/index.f81cc152.css                                  230.69 KiB / gzip: 38.41 KiB
dist/assets/index.0957f648.js                                   1132.42 KiB / gzip: 363.66 KiB
```
Build #1218:  
```
dist/assets/index.a79a9296.css                       33.80 KiB / gzip: 7.36 KiB
dist/assets/index.92eae59b.js                        1077.05 KiB / gzip: 343.86 KiB
```
Old => now:  
- From 1127 KiB to 1110 KiB  
- From 301 KiB to 350 KiB  gzipped

### LINKED ISSUE #1202: Don't expand the semi-circle of archived goal when clicked
**Describe the bug**
In archive, the semi-circle is expanding when clicked.

**To Reproduce**
1. Archive a goal 
2. Open Archive drawer 
3. Click on the archived goal 

**Expected behavior**
Since there is no list of actions for a archived goal, we don't want it to expand.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Android
 - Browser : chrome

### PR DESCRIPTION
**Pull request by Tushar-4781**
Resolves #1163 
Resolves #1202

### CODE REVIEW

**Comment by tijlleenders** [comment]
@Tushar-4781  
Status on size is now:
Old => now:
- From 1127 KiB to 1110 KiB
- From 301 KiB to 350 KiB gzipped  

Maybe we can also get the antd from a CDN?
That could improve load-times if user already visited it for some other page.

**Comment by Tushar-4781** [comment]
@tijlleenders  Check this 
image

**Comment by Tushar-4781** [comment]
> @tijlleenders Check this image

its the scheduler's wasm file

**Comment by tijlleenders** [comment]
Yup I know - there is some room for optimization there... :)

**Review by tijlleenders — APPROVED** [review]
Nice!

**Pull request merged**
