### PR TITLE
Solved the error in the the goalParser

### PR DESCRIPTION
**Pull request by GithinjiHans**

### CODE REVIEW

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Please also make an extra test case for this so it can't get broken accidentally next time someone makes a change.

**Comment by GithinjiHans** [comment]
Screenshot from 2022-05-26 13-30-26

**Comment by GithinjiHans** [comment]
Converted to draft to work on the test case

**Comment by GithinjiHans** [comment]
We will continue updating the GoalParser incase any more bugs are encountered

**Pull request merged**
