### PR TITLE
edit: Update goal circle icon representation

### LINKED ISSUE #1568: Make goal circle used for leaf-goal bigger
**Is your feature request related to a problem? Please describe.**
After differentiating between Goals and Budgets we need a visual cue to show the difference in the goal circle icon.  
This is complicated as the goal icon is quite small, and the way to show sub-goals is to have a bigger circle around it; which would make recognizing the budget icon harder.

**Describe the solution you'd like**
Before making a special goal circle for a budget, switch the logic of signalling sub-goals. Instead of showing a bigger goal circle around the parent goal circle, start with a bigger circle by default for leaf-goals and add a smaller goal circle inside of if in case the goal gets sub-goals.  This seems more intuitive - as the parent 'contains' the sub-goals. It will also be easier to recognize a budget from a goal - while both could contain sub-goals/budgets.

**Describe alternatives you've considered**
None

**Additional context**
Leaf goal before requested change:  
image
This circle has to change to be as big as outer circle of goal with sub-goals (see below).

Goal that has sub-goals before requested change (ignore misalignment; it doesn't happen on mobile):  
image
This representation wouldn't change.

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #1568

### CODE REVIEW

**Comment by tijlleenders** [comment]
@vinaybadgujar102 the outer circle (with the shading) now seems to get smaller when there are subGoals. This is confusing.  

Can you make it so that the outer circle remains the same, but only a small circle without shading gets added its middle when it gets subGoals?

**Comment by tijlleenders** [comment]
LGTM @Tushar-4781 ?

**Review by Tushar-4781 — APPROVED** [review]
Code looks good, btw actions text is barely visible, do we need it ?

**Comment by tijlleenders** [comment]
It's not very readable, I agree. You could zoom in. Another option is to replace it with three dots which are easier to recognize without zooming in. Different issue though!

**Pull request merged**
