### PR TITLE
Feature/goal db save

### LINKED ISSUE #356: Avoid empty 'My goals' page
If someone opens the My goals page without any registered goala it should open the Add goals page instead.

### LINKED ISSUE #452: Store the goal into DB
TODO: In the AddGoals page, the addGoal button should save the goal details into DB.

### PR DESCRIPTION
**Pull request by pulkitvyas08**
Resolves #452 
Resolves #356 

Note regarding #356: at the moment we are redirecting the user to `AddGoals` page even if there are goals in the collection that are archived. This might change if we decide to add the archived goals list to `MyGoals` page itself but since #422 is in the pre-design phase I'm making the assumption that this is the right choice.

### CODE REVIEW

**Comment by tijlleenders** [comment]
Separate issue will have yo be made to fix the visualization on MyGoals. Title and color are not showing - and there is a small square that shouldn't be there.

**Comment by pulkitvyas08** [comment]
> Separate issue will have yo be made to fix the visualization on MyGoals. Title and color are not showing - and there is a small square that shouldn't be there.

Uhh this was all working on my local. Let me check again

**Comment by pulkitvyas08** [comment]
> Separate issue will have yo be made to fix the visualization on MyGoals. Title and color are not showing - and there is a small square that shouldn't be there.

Okay I think it would be better to make a new issue to deal with the UI stuff + validation (to not let empty feelings through) as everything else is working just fine

**Comment by pulkitvyas08** [comment]
@Tushar-4781 Can you look at this cypress failure and tell me what's wrong here. Attaching the screenshot of the failure point. I don't think this is the expected behavior here

DashboardUserChoice Test -- Should have My Feelings button working (failed)

Why should `AddFeelings` path contain "MyFeelings"?

**Comment by Tushar-4781** [comment]
This is happening because of that timeout function since Cypress doesn't found anything in db so the app redirect it to addFeelings this is the reason why Cypress tests have been failing from very beginning.

**Comment by tijlleenders** [comment]
@Tushar-4781 can you make an issue to fix this test? Merging as this PR did what it needed to do and the test is a false negative.

**Pull request merged**
