### PR TITLE
Update artifacts (from script)

### PR DESCRIPTION
**Pull request by tijlleenders**
This PR was automatically generated by the update_artifacts.sh script.

### CODE REVIEW

**Comment by tijlleenders** [comment]
@Tushar-4781 Are we using the wasm scheduler by default?  
Can we remove the JS scheduler from the code - if we haven't already?

**Comment by tijlleenders** [comment]
@Tushar-4781 I notice two new fields in the input JSON: "hoursSpent" and "skippedToday".  
Please remove them. "hoursSpent" might be re-introduced once we get the basic scheduler working again. Let's generate a correct initial schedule before introducing state about what has been completed.

**Comment by tijlleenders** [comment]
Perfect!  
Once https://github.com/tijlleenders/ZinZen-scheduler/issues/382 is done we can have a working integration again. Then we look at the logic...

**Comment by tijlleenders** [comment]
@Tushar-4781 please merge.

**Review by Tushar-4781 — APPROVED** [review]

**Pull request merged**
