### PR TITLE
822/strikethrough goal text when done hide done when revisiting

### PR DESCRIPTION
**Pull request by Nicholas-Kipkoech**

### CODE REVIEW

**Comment by Nicholas-Kipkoech** [comment]
@tijlleenders Can we reduce the time it takes for a goal when marked done to get archived?

**Comment by tijlleenders** [comment]
@Nicholas-Kipkoech You mean that instead of waiting to archive for me to navigate away and come back, we wait XX seconds? That could indeed be an option. But what is the advantage? And what happens if you navigate away when the goal is not archived yet?

**Comment by Nicholas-Kipkoech** [comment]
@tijlleenders  You can still navigate to any other page and the goal will be archived because it is a background process it wont affect other functionalities. The default wait now is 3 seconds we can reduce to 2 seconds maybe?

**Comment by Nicholas-Kipkoech** [comment]
@tijlleenders  You can still navigate to any other page and the goal will be archived because it is a background process it wont affect other functionalities. The default wait now is 3 seconds we can reduce to 2 seconds maybe?

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Ok, this works. Just:  
- from a user perspective, the strikethrough should coincide with the completion sound, not with the move to archive.  
- increase the wait to 10 seconds

**Comment by Nicholas-Kipkoech** [comment]
@tijlleenders noted!

**Review by tijlleenders — APPROVED** [review]
This is good ... for now.  

I realized that with the timeout it might getba little unexpected as goals can change / shift positions unexpectedly.  

Like I said ok for now - but the better option is to have them disappear only after you navigate away.

@Tushar-4781 Please review the code.

**Comment by Nicholas-Kipkoech** [comment]
@tijlleenders For them to disappear when you navigate away is to reduce the delay to 2 seconds because already I have synced the sound with line stroke

**Comment by tijlleenders** [comment]
@Nicholas-Kipkoech That is not what I meant. I meant that ideally, the goals stay crossed out, forever, until you navigate away.

**Comment by tijlleenders** [comment]
@Tushar-4781 *bump*

**Review by Tushar-4781 — APPROVED** [review]

**Pull request merged**
