### PR TITLE
persist goal title translation across app

### LINKED ISSUE #1754: Default goals translation does not persist
**Is your feature request related to a problem? Please describe.**
It's very annoying when translated default goals change their language when editing or sending to the scheduler.

**Describe the solution you'd like**
Make sure the translated default goals that are used upon initialization of the app actually persist.

**Describe alternatives you've considered**
None.

**Additional context**
image

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #1754

### CODE REVIEW

**Review by tijlleenders — CHANGES_REQUESTED** [review]
When I start the app in Dutch, then edit 'Slapen' I see 'Sleep' in the title of the edit modal...

**Comment by vinaybadgujar102** [comment]
> When I start the app in Dutch, then edit 'Slapen' I see 'Sleep' in the title of the edit modal...

[Screencast from 11-01-24 01:23:08 PM IST.webm](https://github.com/tijlleenders/ZinZen/assets/90821253/7712d5c1-b603-442c-8283-328209bbd5d9)


I think the issue to solved or am I missing something?

**Review by tijlleenders — CHANGES_REQUESTED** [review]
@vinaybadgujar102 When I click on Daily habits in Dutch, then click on the title on the Goal menu (not the edit screen) - I thereafter get errors and the English title keeps appearing again.

image

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Translated titles are also not sent to scheduler (Tasks in English).

**Comment by vinaybadgujar102** [comment]
@tijlleenders , when a new user visits our app and is onboarding, we currently store goals in English by default in our db on the onboarding page before language selection. Would it make sense to store these goals in the user's selected language after user selects language

**Comment by tijlleenders** [comment]
@Tushar-4781 What pattern is appropriate here? Translate goals or store a separate set of default goals for each language?  
I'm leaning to separate - and if possible only load when required.

**Comment by Tushar-4781** [comment]
> @Tushar-4781 What pattern is appropriate here? Translate goals or store a separate set of default goals for each language? I'm leaning to separate - and if possible only load when required.

no i think its quite straight forward. where every the translation is required just   
1. extract like this const { t } = useTranslation();
2. use this t function to convert any text if its translation is present it will be translate otherwise it will be show whatever is written simple

**Review by Tushar-4781 — CHANGES_REQUESTED** [review]
image

@vinaybadgujar102 can you please fix this

**Comment by vinaybadgujar102** [comment]
> @vinaybadgujar102 Translated titles are also not sent to scheduler (Tasks in English).

fixed

**Comment by tijlleenders** [comment]
> > @vinaybadgujar102 Translated titles are also not sent to scheduler (Tasks in English).
> 
> fixed, also the setting dropdown width problem is solved in another pr.

Was the dropdown width broken by this PR or is it logically part of this feature? Then it should be fixed in this PR. A PR shouldn't regress the app - even if there is some other PR fixing it. We shpuld think about PRs atomically as much as possible. Coupling them between each other increases complexity.

**Comment by vinaybadgujar102** [comment]
@tijlleenders the dropdown width was broken in #1747. as Tushar gave review about the width being broken on all the PRs (https://github.com/tijlleenders/ZinZen/pull/1732#pullrequestreview-1820006123, https://github.com/tijlleenders/ZinZen/pull/1736#pullrequestreview-1820004501) I fixed it in #1732 only.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Please apply the fix to all PRs that are blocked by this.  

Ideally this would be logged as a separate issue (regression effect of already merged PR) - with a new PR adressing just that issue - so that it gets into main without being bothered by reviews on other changes.

**Review by tijlleenders — APPROVED** [review]
LGTM!

**Review by Tushar-4781 — APPROVED** [review]

**Pull request merged**
