### PR TITLE
fix:remove webpack deps

### PR DESCRIPTION
**Pull request by Nicholas-Kipkoech**

### CODE REVIEW

**Comment by tijlleenders** [comment]
@Nicholas-Kipkoech Did you test the preview link? It's not working for me.

**Comment by Nicholas-Kipkoech** [comment]
@tijlleenders  I have tested it and it is working as expected.
Screenshot 2024-07-21 125755

**Comment by tijlleenders** [comment]
Did you clear cookiea and cache and start from the language selection? I just noticed this failing on main too.

**Comment by Nicholas-Kipkoech** [comment]
@tijlleenders Let me bring back the removed dependencies and try previewing again to check if that was the issue.

**Comment by tijlleenders** [comment]
I don't think so, as it is already present in main. You can remove the webpack dependencies again.

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Please remove dependencies, the bug is unrelated, filed #1962 separately. Will merge this.

**Comment by Nicholas-Kipkoech** [comment]
@tijlleenders noted!

**Comment by Nicholas-Kipkoech** [comment]
@tijlleenders I think the issue is the label wont register an event until you click on that circle next to the language label then it works.

**Comment by tijlleenders** [comment]
Yes, it should react anywhere, not just the circle.

**Comment by Nicholas-Kipkoech** [comment]
@tijlleenders This is done.

**Review by tijlleenders — APPROVED** [review]
Thanks!

**Pull request merged**
