### PR TITLE
modal buttons position switched

### PR DESCRIPTION
**Pull request by Shubham-Praj**
This resolves issue #1190 

Old Modal Screenshot 
old modal ss

New Modal Screenshot 
UpdatedSS

### CODE REVIEW

**Comment by tijlleenders** [comment]
Thanks @Shubham-Praj !

@Tushar-4781 Should the styling of the confirm button be white (like create goal and language choice) or pinkish (like confirn is now) in light theme?
It's not consistent...

**Comment by Tushar-4781** [comment]
@tijlleenders button that perform certain actions or submissions are always supposed to vary from the entire layout background. it helps user to distinguish without putting much focus on text. if we make it consistent with the rest of color then user needs to put a little focus on both buttons to identify which one is **confirm**.  Lemme know if you want to alter that

**Review by Tushar-4781 — APPROVED** [review]

**Comment by tijlleenders** [comment]
@Tushar-4781 That's not what I mean.
I agree with this - that's what I asked for. I mean the way we highlight certain buttons is different _across screens_. In light mode sometimes we highlight with white - sometimes with darker color.

**Comment by Tushar-4781** [comment]
> @Tushar-4781 That's not what I mean. I agree with this - that's what I asked for. I mean the way we highlight certain buttons is different _across screens_. In light mode sometimes we highlight with white - sometimes with darker color.

yes its completely upto theme background and other component's background too like pop-up modals, bottom nav etc.
we have to keep minimum colors for each theme.

**Pull request merged**
