### PR TITLE
695-completing-goal-twice-adds-it-to-archive-twice

### PR DESCRIPTION
**Pull request by fendermany**
Have a good day!

I solved the problem.

### CODE REVIEW

**Review by Tushar-4781 — COMMENTED** [review]
Ouch !! lmao, Sorry @tijlleenders I forgot we are open-source. @fendermany we can't merge it atm. #868 has to be merged first. Sorry for holding this PR.

**Comment by tijlleenders** [comment]
Hi Dmitry,
Thanks for your PR.

Would you mind giving every commit a good description?
Also please check the formatting with @Tushar-4781 - it is really not clear what you did with all the formatting diffs.
Finally please don't introduce files/objects called 'Custom' - it is not very descriptive.

Without these changes it is not possible to review your work efficiently.

**Comment by tijlleenders** [comment]
Also, please don't include any commits not directly related to fixing the issue.
For example: adding dependencies or changing package versions.

**Comment by tijlleenders** [comment]
This needs to be redone from scratch - with only descriptive commits that are required for the fix - and correct formatting.

**Comment by fendermany** [comment]
> Also, please don't include any commits not directly related to fixing the issue. For example: adding dependencies or changing package versions.

Hello Tijl,

I'm sorry, I just wanted to test because of which the tests fail

**Comment by fendermany** [comment]
> Hi Dmitry, Thanks for your PR.
> 
> Would you mind giving every commit a good description? Also please check the formatting with @Tushar-4781 - it is really not clear what you did with all the formatting diffs. Finally please don't introduce files/objects called 'Custom' - it is not very descriptive.
> 
> Without these changes it is not possible to review your work efficiently.

@Tushar-4781 

Hello Tushar,

Can you share with me the actual prettier settings?

Nice to meet you.

**Pull request closed without merging**
