### PR TITLE
feat: add active effect to focus timer

### LINKED ISSUE #1834: Show seconds along with the minutes in schedule focus
**Is your feature request related to a problem? Please describe.**
It's very boring when we start the focus timer and see no changes before the next min

**Describe the solution you'd like**
Show seconds along with the minutes. 

The quick changes in the UI will help us stay focus not bored

**Describe alternatives you've considered**
none

**Additional context**

https://github.com/tijlleenders/ZinZen/assets/117534561/1157c086-c52e-4697-ada3-1b37d00ca530

### PR DESCRIPTION
**Pull request by mehedihasan2810**
closes #1834 

@tijlleenders 

https://github.com/tijlleenders/ZinZen/assets/117534561/800e19c9-8530-4b81-ab07-01a0eb6c7632

### CODE REVIEW

**Comment by tijlleenders** [comment]
Thanks @mehedihasan2810 !

Excellent. So we now have a bomb timer at the end, haha :)  
That's fine by me - as long as it's not constantly ticking during the 20+ minutes.  

I struggled to see the animation effect you added. In the beginning when setting 20-something minutes, the elapsed duration is very small.  

I suggest trying to put the 'glow' animation on the entire circle to make it more obvious when the elapsed time is short. Maybe even make the glow pulsate through the circle ... but that might be hard to do.  

In terms of speed - I think we can go a little slower - like a yoga breathing exercise (or at leastt my perception of it). Breathe in ... 3 seconds ... hold 1 seconds ... breathe out 4 seconds... - or something similar.

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Thanks @mehedihasan2810 !

Excellent. So we now have a bomb timer at the end, haha :)
That's fine by me - as long as it's not constantly ticking during the 20+ minutes.

I struggled to see the animation effect you added. In the beginning when setting 20-something minutes, the elapsed duration is very small.

I suggest trying to put the 'glow' animation on the entire circle to make it more obvious when the elapsed time is short. Maybe even make the glow pulsate through the circle ... but that might be hard to do.

In terms of speed - I think we can go a little slower - like a yoga breathing exercise (or at leastt my perception of it). Breathe in ... 3 seconds ... hold 1 seconds ... breathe out 4 seconds... - or something similar.

**Comment by mehedihasan2810** [comment]
hey @tijlleenders I get it what UI should be appropriate in this scenario
but as it is a svg progress circle so it is kind of difficult for me to add that kind of svg animation/effect.
So I would like to work on it later after I explore some resources on svg animation. you can mark it as a draft till then.

For now can I take look at other issues? Thanks

**Comment by tijlleenders** [comment]
@mehedihasan2810 Sure.

The glow-animation doesn't _have_ to be on the circle. You could also just play with the background gradient or something - just to show some movement.

**Comment by tijlleenders** [comment]
Closing this due to inactivity @mehedihasan2810

Thanks for trying - and feel free to re-open if you have time.

**Pull request closed without merging**
