### PR TITLE
Inner circle alignment fixed

### LINKED ISSUE #1412: Fixed alignment title when expanding goal
**Is your feature request related to a problem? Please describe.**
It's very annoying when alignment of the title is broken when expanding a goal.

**Describe the solution you'd like**
Always keep title aligned with middle of the goal circle.

**Describe alternatives you've considered**
None.

**Additional context**

### PR DESCRIPTION
**Pull request by Shubham-Praj**
Resolves #1412 

image

### CODE REVIEW

**Comment by tijlleenders** [comment]
@Shubham-Praj This looks good - why did you close it if I may ask?

**Comment by tijlleenders** [comment]
@Tushar-4781 @Shubham-Praj You both started working on this around the same time - it's important to self-assign an issue you'd like to work on to avoid disappointment... it's an open project :)

**Comment by Shubham-Praj** [comment]
@tijlleenders Really sorry I will assign myself when ever working on issue

The fix that I made is fixing the alignment of the inner circle, not the title. I missed the title part, my bad. That's why i close the pr so there's no issue in code

**Comment by tijlleenders** [comment]
Sure no problem, luckily it's a minor issue so no frustration anywhere I hope :)
Just to avoid duplicating work...

**Comment by Shubham-Praj** [comment]
Sure

**Pull request closed without merging**
