### PR TITLE
[Issue #1531] || fix darkmode toggle bug

### PR DESCRIPTION
**Pull request by devndevs**
Description of the Original Issue
As detailed in https://github.com/tijlleenders/ZinZen/issues/1531, the problem appears to be related to the quick toggle feature to switch between dark and light modes. The Icon would disappear depending on what time it was, in the case of the example shown it was when the nighttime logic was active, as I tested it the nighttime logic was not active so the opposite was happening to me  (absence of dark mode icon)

Implemented Solution
I changed the logic to show the opposite icon regardless of what time it was on the user's computer.

### CODE REVIEW

**Comment by tijlleenders** [comment]
So sorry @devndevs I should have marked the issue as "won't fix".  
The comments say it's not a bug. If you believe it is - please vote on the issue.

**Review by tijlleenders — APPROVED** [review]
As @devndevs suggested I'll make an issue to remove the quick toggle so we can declutter the header - and make dark mode the default.

**Comment by tijlleenders** [comment]
For now we can use this. I'll pay attention to my own needs - I usually only use dark mode - so based on n=1 @devndevs right :)

**Review by Tushar-4781 — APPROVED** [review]
Thanks for fixing this @devndevs

**Pull request merged**
