### PR TITLE
Add helper module that filters tasks according to start day.

### LINKED ISSUE #889: Create module that filters tasks per day

### PR DESCRIPTION
**Pull request by egithinji**
Closes #889 .

### CODE REVIEW

**Review by Tushar-4781 — COMMENTED** [review]
It may not be serving the purpose. But would you like to try why the MyTime page is showing only 2 tasks?  earlier they all were schedulable now we see only 2.

**Comment by egithinji** [comment]
> It may not be serving the purpose. But would you like to try why the MyTime page is showing only 2 tasks? earlier they all were schedulable now we see only 2.

Sure. Is there already an issue for this problem?

**Comment by egithinji** [comment]
> It may not be serving the purpose. But would you like to try why the MyTime page is showing only 2 tasks? earlier they all were schedulable now we see only 2.

Sure. Is there already an issue for this problem?

**Comment by tijlleenders** [comment]
@egithinji If integrating this module to the frontend is not part of this PR can you make a separate issue for that?

Is this test part of the CI now?

**Comment by Tushar-4781** [comment]
> > It may not be serving the purpose. But would you like to try why the MyTime page is showing only 2 tasks? earlier they all were schedulable now we see only 2.
> 
> Sure. Is there already an issue for this problem?

nope

**Comment by tijlleenders** [comment]
> > > It may not be serving the purpose. But would you like to try why the MyTime page is showing only 2 tasks? earlier they all were schedulable now we see only 2.
> > 
> > 
> > Sure. Is there already an issue for this problem?
> 
> nope

I think we don't need a new issue for this - just solve it as part of #742

**Review by Tushar-4781 — APPROVED** [review]
let's if these module can help else we will remove it in next refractoring

**Pull request merged**
