### PR TITLE
Re-Developed: Feature - My feelings

### LINKED ISSUE #835: Re-develop the my feelings page

### PR DESCRIPTION
**Pull request by Tushar-4781**
Resolves #835

### CODE REVIEW

**Comment by tijlleenders** [comment]
The PR might be exactly what is on the roadmap - but as a user I have a few comments.

We can decide to make new issues for this and merge the PR - as the basic functionality works - or fix it now and be done with it.

1. Side menu Feelings not translated
2. Input 'You feel...' and 'Can you be more specific?' not translated
3. 'Done' button font is white in dark theme - I thought Tushar and Mallika decided to use black font in both the dark and light theme (even though it seems to go against convention)?
4. After adding a feeling for today I can't add another.
5. There is no visual difference in note icon between no note yet and having previously entered a note.
6. 'You feel..." shouldn't that be 'I feel'?
7. There is no greyed-out emoji on MyTime to add a feeling from there. I still feel that adding a feeling should also be possible from + button - not only the emoji or the side-menu=>Feelings
8. Mallika has designed new category 'Tired' because many people asked for it. Can we add this?

**Review by tijlleenders — DISMISSED** [review]

**Comment by Tushar-4781** [comment]
> The PR might be exactly what is on the roadmap - but as a user I have a few comments.
> 
> We can decide to make new issues for this and merge the PR - as the basic functionality works - or fix it now and be done with it.
> 
> 1. Side menu Feelings not translated
> 2. Input 'You feel...' and 'Can you be more specific?' not translated
> 3. 'Done' button font is white in dark theme - I thought Tushar and Mallika decided to use black font in both the dark and light theme (even though it seems to go against convention)?
> 4. After adding a feeling for today I can't add another.
> 5. There is no visual difference in note icon between no note yet and having previously entered a note.
> 6. 'You feel..." shouldn't that be 'I feel'?
> 7. There is no greyed-out emoji on MyTime to add a feeling from there. I still feel that adding a feeling should also be possible from + button - not only the emoji or the side-menu=>Feelings
> 8. Mallika has designed new category 'Tired' because many people asked for it. Can we add this?

1. & 2. The language translate issue is there on multiple components. Will deal with this in another issue dedicated for this.
3. Nope, the done text will be white for dark; black for light
4. alright will fix this 
5. new issue for this which @mallikarai05 can resolve 
6. cool
7 will be dealt in new PR for the MyTime page
8. hmm... does it contain multiple options like other categories like happy has loved, relieved, ...

**Comment by mallikarai05** [comment]
@tijlleenders @Tushar-4781 
1. & 2. After getting done with the 2 design issues, I can work on the translations.
3. The text being black is only limited to the goals, all the UI components would follow the conventions. I have already checked the contrast for the 'Done' button.
4. I will work on it, and will update you as soon as it's done.
6. Will change this
7. the + on top right?
8. Tushar can work on this!

**Comment by tijlleenders** [comment]
@Tushar-4781 @mallikarai05 
Please double check your numbering. 
It is supposed to ease communication, not complicate it :)

**Comment by Tushar-4781** [comment]
@mallikarai05 😅 i need the assist on 4th point only 🤣

**Comment by tijlleenders** [comment]
Great, we can log feelings again!

**Review by tijlleenders — APPROVED** [review]
This alone is massively valuable for a lot of people!

**Pull request merged**
