### PR TITLE
Toggle Task Open/Close and Add Goal Navigation Button

### LINKED ISSUE #1765: Open close MyTime Tasks by clicking on title.
**Is your feature request related to a problem? Please describe.**
It's very annoying when you expect something and something else happens. Many users expect the Tasks to open/close (uncollapse/collapse) by clicking on the title.  
Rught now clicking on the title will take you to the Goal that created the Task on MyGoals.

**Describe the solution you'd like**
Open/close Task when clicking on Task title on MyTime.  
Add a 'Goal' option in the Task options that will take you to the Goal.

**Describe alternatives you've considered**
An option modal that only opens when clicking on the Task ball. This is consistent with the My Goal page and can provide bigger buttons.  
Too much work for now?

**Additional context**
None.

### PR DESCRIPTION
**Pull request by Jayanth-Parthsarathy**
### Pull Request Description:
Resolves #1765

### Changes Made:
Modified the title functionality to allow toggling the Task open and close as requested.
Added a new button within the action buttons to enable users to navigate directly to the associated Goal page.

Please review the changes and provide feedback. Let me know if any adjustments are needed. I'm open to making further modifications as required.

### CODE REVIEW

**Review by tijlleenders — APPROVED** [review]
Excellent @Jayanth-Parthsarathy , thanks!

@Tushar-4781 OK on code?

**Review by Tushar-4781 — CHANGES_REQUESTED** [review]
welcome @Jayanth-Parthsarathy , glad to see you contributing, can you fix this ?
image

**Comment by tijlleenders** [comment]
@Jayanth-Parthsarathy @Tushar-4781 

I think the view is OK on mobile, I found no issue.  
The Tasks buttons are being scrolled/cut off on desktop viewing only.  
It would be nice to fix this if not a lot of trouble. Scrolling is not the solution - so disallow the scroll or force some other solution to be preferred.

**Comment by Jayanth-Parthsarathy** [comment]
@tijlleenders sure let me do that.

**Comment by Jayanth-Parthsarathy** [comment]
@tijlleenders, @Tushar-4781. Please have a look and let me know if any more changes are to be made!

**Comment by tijlleenders** [comment]
Thanks for persisting @Jayanth-Parthsarathy !

Now the desktop view works fine - but the mobile view is broken.  
image

Please let us know if you need assistance.

**Comment by Jayanth-Parthsarathy** [comment]
Sure let me look into this

**Comment by Jayanth-Parthsarathy** [comment]
@tijlleenders @Tushar-4781 Please have a look at this and feel free to let me know if I need to make any further changes.

**Comment by tijlleenders** [comment]
Cool @Jayanth-Parthsarathy Glad you figured out a way!

Could you just remove the last trailing |? I see no use for it.
image
 
@Tushar-4781 Good to merge the code after that?

**Review by tijlleenders — APPROVED** [review]
Thanks, @Jayanth-Parthsarathy nice work.

**Comment by Jayanth-Parthsarathy** [comment]
@tijlleenders Removed the last '|' as you requested. Anything else to be changed do let me know!

**Review by Tushar-4781 — APPROVED** [review]

**Pull request merged**
