### PR TITLE
change UI of tasks in My Time page 

### LINKED ISSUE #1766: Change display of Tasks
**Is your feature request related to a problem? Please describe.**
It's very annoying when you can't see the times on the overview/list of Tasks. You have to uncollapse each one individually to see the time.

**Describe the solution you'd like**
- Move the starting time to where the Task ball is.
- Move the ball to a rounded line on the edge of the screen, keeping the Task color.
- Only show the ending time when uncollapsed, on bottom of Task row, aligned with starting time.

**Describe alternatives you've considered**
None.

**Additional context**

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #1766

### CODE REVIEW

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Yeah this is a great improvement!  

Could you stick the vertical bars to the edge of the screen (0 margin)?

**Comment by vinaybadgujar102** [comment]
> Could you stick the vertical bars to the edge of the screen (0 margin)? 

@tijlleenders, like this?

Screenshot from 2024-01-20 15-37-38

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Yeah, that's what I mean, but then I'd like to align everything as much as possible - also saving space:
image
  

It doesn't look quite right yet - but this is the right direction.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 
The vertical pills are less busy when not rounded on both sides - more like tabs:
image

**Comment by vinaybadgujar102** [comment]
>  The vertical pills are less busy when not rounded on both sides - more like tabs:

@tijlleenders , then it will be ideal to decrease the width of the color tab

Screenshot from 2024-01-20 16-22-28

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Yeah but sharp square edges are a no-go design wise. If you can round them on the right side then it's great.

**Comment by vinaybadgujar102** [comment]
@tijlleenders made the requested changes. please review

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Excellent!

We're nearly there :)

Just some alignment left: 


This wilk make the screen a little less busy - and give somw more space.

**Comment by vinaybadgujar102** [comment]
@tijlleenders made changes

**Comment by tijlleenders** [comment]
Wow @vinaybadgujar102 This is turning out great!

Juat one more request - while we're at it :)

The hours are a bit small to read - and in expanded mode the difference is nit really visible.

Can we :
- make the starting hours (in green) conform to font size of the title?
- make the ending hours (in red) not bold (same size/type as the goal action buttons)?

**Comment by vinaybadgujar102** [comment]
@tijlleenders made the requested changes

**Review by tijlleenders — APPROVED** [review]
Excellent @vinaybadgujar102 !

I have more ideas - but let's get this in and iterate.

@Tushar-4781 OK on code?

**Pull request merged**
