### PR TITLE
Added  ® to all Zinzen occurences where neccessary.

### PR DESCRIPTION
**Pull request by GithinjiHans**

### CODE REVIEW

**Comment by tijlleenders** [comment]
@GithinjiHans Can you also do the readme?

**Comment by tijlleenders** [comment]
It is actually pretty ugly to have the big R everywhere, especially with this font. 
Can you try to make it smaller, less obvious?

**Comment by GithinjiHans** [comment]
> It is actually pretty ugly to have the big R everywhere, especially with this font. Can you try to make it smaller, less obvious?

Or maybe make it superscript if possible

**Comment by mallikarai05** [comment]
@tijlleenders Sure, I'll try something out

**Comment by tijlleenders** [comment]
Size is a lot better.
Positioning?

**Comment by GithinjiHans** [comment]
> Size is a lot better. Positioning?
> 
> 

We can only design the R individually and the multilanguage feature makes it even more complicated because the position of the word ZinZen is different. For now we can just use the R in the userchoice dashboard and delete the others in other pages then rethink of how to go about that.

**Comment by tijlleenders** [comment]
Ok good work.
Indeed we should not invest too much in making this possible. 

Removing the occurences by rephrasing good be an option, for example:
- "Quick intro"
- "Skip intro"

**Comment by GithinjiHans** [comment]
> Ok good work. Indeed we should not invest too much in making this possible.
> 
> Removing the occurences by rephrasing good be an option, for example:
> 
>     * "Quick intro"
> 
>     * "Skip intro"

Good idea...so we should use this PR for that..right??

**Comment by tijlleenders** [comment]
Sure!

**Comment by tijlleenders** [comment]
@Tushar-4781 Can you assist with the failing  test (see last 3 commits)?

**Review by Tushar-4781 — COMMENTED** [review]
The tests are failing because of the update "Skip intro". We have to update all the tests not just the dashboard,

**Review by tijlleenders — APPROVED** [review]

**Pull request merged**
