### PR TITLE
Add visual glow to navigated goal

### LINKED ISSUE #1354: Add visual effect to Goal when opening through click on MyTime Task
**Is your feature request related to a problem? Please describe.**
It's very annoying when I click through to Goals from MyTime and I have to search where it is on the screen between the other Goals.

**Describe the solution you'd like**
Add a visual effect like a quick glow or soft flash so that my eyes are automatically drawn to the place on screen where the Goal is.

### PR DESCRIPTION
**Pull request by Jayanth-Parthsarathy**
Pull Request: Enhancing User Experience with Temporary Visual Highlight
Description:
Resolves #1354 
This pull request addresses the need for improved user experience when navigating from the MyTime page to the GoalsPage. To facilitate easier goal identification, I have implemented a temporary visual highlight effect on the selected goal.

image

### CODE REVIEW

**Comment by tijlleenders** [comment]
Thanks @Jayanth-Parthsarathy 

Is it possible to animate this?  
Without animation/movement it still doesn't attract (enough) attention.

**Comment by Jayanth-Parthsarathy** [comment]
> Thanks @Jayanth-Parthsarathy 
> 
> Is it possible to animate this?  
> Without animation/movement it still doesn't attract (enough) attention.

Sure will do this

**Comment by Jayanth-Parthsarathy** [comment]
Hey @tijlleenders. I have made some changes to the CSS animation to make it more eye catching. Please have a look and let me know if you need anything else.

**Comment by tijlleenders** [comment]
@Jayanth-Parthsarathy Yeah this is WAY better.  

Could you change the subject of the highlight to be the Goal title instead of the summary?  

Then we can move on to technical review - and merge.  

I'll make a separate issue for scrolling towards the relevant Goal in a long list. Currently you'll not see the highlight for defaukt Goal 'Sleep' on some devices - as it is off-screen at the bottom of the list.

**Comment by Jayanth-Parthsarathy** [comment]
Hey @tijlleenders. I have made some changes to the CSS and have highlighted the goal title instead of the subject. Do let me know if I need to change anything else.

**Comment by tijlleenders** [comment]
Thanks @Jayanth-Parthsarathy 

My attention is now automatically directed towards the item!  

Using a border animation results in a 'jump' in positioning - which is quite distracting/concerning.  

To avoid this I believe it's better to animate the background color of the Goal title for about a second in total. Could you try that?

**Comment by Jayanth-Parthsarathy** [comment]
@tijlleenders, I have removed the padding during animation that makes the goal title jump as you have asked. Do let me know if you need me to make any further changes.

**Comment by tijlleenders** [comment]
Yeah - I'd still prefer it on the background - and for the whole horizontal bar including the circle... Now we see hard/pointy corners - which is against the design guidelines.

If you're willing to try that please - otherwise I'll ask for a technical review. Something is better than nothing.

**Comment by Jayanth-Parthsarathy** [comment]
@tijlleenders Sure thing. Let me work on it.

**Comment by tijlleenders** [comment]
@Jayanth-Parthsarathy Great, something similar to the long press effect, but with gradual animation on/off:  



The glow can stay - I think it'll be nice if combined with the background effect.

**Comment by tijlleenders** [comment]
Perfect @Jayanth-Parthsarathy !

Just make it 500ms in total and we're good!

**Comment by Jayanth-Parthsarathy** [comment]
@tijlleenders Reduced the time for animation as you have asked. Do let me know if you need me to make any changes.

**Review by tijlleenders — APPROVED** [review]
Thanks @Jayanth-Parthsarathy this is great.

@Tushar-4781 OK on the code?

**Pull request merged**
