### PR TITLE
Fix: Not detecting @ in start/by 12/3 @15

### LINKED ISSUE #706: Handle start and deadline @time
@Tushar-4781 I'm confused.

start and deadline are datetime fields right?
So we could type 'start 22/11 @13'.

If yes, this doesn't seem to be implemented yet so this issue is for adding that to the parser.

### PR DESCRIPTION
**Pull request by Tushar-4781**
Resolves #706

### CODE REVIEW

**Comment by tijlleenders** [comment]
Works for due but not for start.

Reproduce: 
start clean, edit exercise add @4 after start, doesn't work. 
Add @4 after due and only due works, see screenshot result:

**Comment by tijlleenders** [comment]
Interestingly, removing the after tag solves the start issue.

**Comment by Tushar-4781** [comment]
> Interestingly, removing the after tag solves the start issue.

@tijlleenders yes after is something you are mentioning explicitly just like inline CSS lol overrides the @

**Comment by tijlleenders** [comment]
Ha, ok it was unexplained behavior :)
We'll have to think about what to do with impossible/weird combinations at some point... but not now.

Does the 'fix' still need to be merged?

**Comment by Tushar-4781** [comment]
> Ha, ok it was unexplained behavior :) We'll have to think about what to do with impossible/weird combinations at some point... but not now.
> 
> Does the 'fix' still need to be merged?

its your call

**Comment by tijlleenders** [comment]
Well if the changes don't actually fix anything - then no, I'll close the PR and issue. 

I've made #708 to think out if this is the right approach for the goalparser implementation.

**Pull request closed without merging**
