### PR TITLE
Feature/render feelings

### PR DESCRIPTION
**Pull request by pulkitvyas08**
Part of #312 

I mentioned in the last meeting that displaying stored feeling is working but then checking with the deployed dev I found that I never pushed the fix so here it is. 

Also fixed the emoji issue on add feelings page (that no one caught till now AFAIK, showing that the test coverage of the UI is pretty bad at the moment)

### CODE REVIEW

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Good catch! Agree that it is time to start using auto UI tests.
We can announce and explain this in the next meeting.

We previously set up Cypress but we're not using it. I made #341 to create a list of the UI tests that we'll need and how to integrate them to the development process. It should be possible to run them locally but not auto-run on every local commit.

Tested this manually - and for mobile (we design develop for mobile only at the moment) the emoji's are not rendering.

If you fix that I can merge.

**Comment by tijlleenders** [comment]
This PR is useful - but will not close #312

**Comment by pulkitvyas08** [comment]
> This PR is useful - but will not close #312

Yes, that was never the intention. I wrote 

> Part of https://github.com/tijlleenders/ZinZen/issues/312

Above instead of `resolves #312`

**Comment by pulkitvyas08** [comment]
> Tested this manually - and for mobile (we design develop for mobile only at the moment) the emoji's are not rendering.
> 
> If you fix that I can merge.

Yupp, my bad, never checked it for mobile

That is fixed now though

**Review by tijlleenders — APPROVED** [review]

**Pull request merged**
