### PR TITLE
Included edit functionality in journal notes

### LINKED ISSUE #1720: Note in Journal is not editable
**Describe the bug**
In Journal page, the note is not editable once saved. 

**To Reproduce**

1. Go to Journal
2. Click on edit button for any feeling
3. The note is not editable

**Expected behavior**
The note should be editable.

**Screenshots**
Screenshot from 2023-12-26 15-06-32

**Desktop (please complete the following information):**
- OS: Ubuntu
- Browser: chrome
- Version 120.0.6099.109 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by mukul7661**
resolves #1720

### CODE REVIEW

**Review by tijlleenders — APPROVED** [review]
Yeah this works @mukul7661 thanks!

@Tushar-4781 OK on code?

**Comment by mukul7661** [comment]
> Yeah this works @mukul7661 thanks!

Welcome

**Review by Tushar-4781 — APPROVED** [review]
Thanks @mukul7661 
this also made use realize Feelings Page is getting overly crowded. some states can be re-utilized for editing & adding note.

**Comment by mukul7661** [comment]
> Thanks @mukul7661 this also made use realize Feelings Page is getting overly crowded. some states can be re-utilized for editing & adding note.

Sure will look into it and try to improve.

**Pull request merged**
