### PR TITLE
code snippets

### PR DESCRIPTION
**Pull request by Nicholas-Kipkoech**

### CODE REVIEW

**Comment by Nicholas-Kipkoech** [comment]
@vinaybadgujar102 I worked on a certain action it copies the code to clipboard but it is not showing the message. Can you look at it?

**Comment by Nicholas-Kipkoech** [comment]
```Js const copyCode = (goalTitle: string) => {
    showMessage("Code copied to clipboard", goalTitle);
    navigator.clipboard.writeText(removeBackTicks(goalTitle));
  }

**Comment by vinaybadgujar102** [comment]
@Nicholas-Kipkoech The issue was caused by click event on  goal title propagating upward to app level, triggering the document click handler in 'App.tsx' that closes the toast notification. Added e.stopPropagation() to prevent it.

**Comment by Nicholas-Kipkoech** [comment]
@vinaybadgujar102 Thanks so much. Let me check it out!

**Comment by vinaybadgujar102** [comment]
Please ask for review from Tijl amd Tushar

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Please redo this PR, based on the current develop branch.  

This PR is hard to review, as you merged an unrelated PR #1967 in too.

**Pull request closed without merging**
