### PR TITLE
edit no duration text

### LINKED ISSUE #1730: Add explanation in goal sub-text
**Is your feature request related to a problem? Please describe.**
It's very annoying when you don't know where to click as a first user.

**Describe the solution you'd like**
Whenever there is a goal without duration - instead of showing the subtext 'No duration', show the text 'Click again to enter - or click the circle to edit.'

**Describe alternatives you've considered**
A tour component. This interrupts the user flow and is suitable for initial tour - not while navigating.

**Additional context**

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #1730

### CODE REVIEW

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Thanks!

1. Now that I see it in Dutch, it is better on two lines.
2. Please also change the first Dutch sentence to 'Klik om een niveau dieper te gaan'
image
3. It doesn't seem to work on the Daily habits default goal?

**Comment by vinaybadgujar102** [comment]
> It doesn't seem to work on the Daily habits default goal?

@tijlleenders, in PR #1713,  id field was removed from all starter goals, because of that sub-goal items are not present in "Daily Habits" goal. 

We have to create new issue to add id field back.

**Comment by tijlleenders** [comment]
@Tushar-4781 Please advise. We can't flip-flop between having an id and not having an id for starter goals. We need to understand why it was removed. Maybe generatong a random uuid on startup is an option?

**Comment by tijlleenders** [comment]
@vinaybadgujar102 
Great, can you also make sure this doesn't show when there is a due date already set?

**Comment by vinaybadgujar102** [comment]
@tijlleenders made the requested changes

> @vinaybadgujar102 Great, can you also make sure this doesn't show when there is a due date already set?

**Review by tijlleenders — APPROVED** [review]

**Review by Tushar-4781 — APPROVED** [review]

**Pull request merged**
