### PR TITLE
Fix/my time page

### PR DESCRIPTION
**Pull request by egithinji**
Related to #742 .
There were three issues, 2 solved with this pr, 1 not yet solved.
1) The 'repeat' value was not being included in the input being passed to scheduler
2) The syntax used for 'repeat' wasn't what scheduler expects (should be all lower case i.e. "daily" not "Daily")

Now the scheduler gives the expected output, but the front end puts them all on the first day. This is the next thing to be fixed.

### CODE REVIEW

**Review by Tushar-4781 — COMMENTED** [review]
ok so now its returning 45 goals, is this how all 7 days schedule is returned ?

**Comment by egithinji** [comment]
Yes if you look at the input and output, you can verify each but I did a spot check and believe it's returning what's expected. For example "Water the plants indoors" has three tasks on three different days, and the goals that are daily have a task for each day.

**Comment by Tushar-4781** [comment]
> 
we are not expecting everything in one array. every day schedule should be separate.
{
dayName: "Tuesday",
Schedule: [ ... ]
impossible: [ ... ]
}
in the above format. so array of seven object each object has schedule of that respective day. let's have a quick call if something is unclear

**Comment by egithinji** [comment]
@Tushar-4781 I don't think this is the best way of approaching displaying the 7 day timeline.

- It makes things very rigid and locks us into this 7 day display. For example we'll be prevented from extending the timeline beyond 7 days simply to avoid the problem of distinguishing between "Tuesday" of this week and "Tuesday" of another week.
- Grouping tasks for a specific day is more of a presentation/display issue and should be done on the front end for maximum maintainability and flexibility, not in the scheduler, whose responsibility is implementing the scheduling algorithm
- Working with strings like "Tuesday" is error-prone and less flexible than working with the actual `Date()`s or numbers of days

I suggest this logic gets worked into the front end, perhaps making use of the `TaskFilter` module.

**Comment by Tushar-4781** [comment]
> @Tushar-4781 I don't think this is the best way of approaching displaying the 7 day timeline.
> 
> * It makes things very rigid and locks us into this 7 day display. For example we'll be prevented from extending the timeline beyond 7 days simply to avoid the problem of distinguishing between "Tuesday" of this week and "Tuesday" of another week.
> * Grouping tasks for a specific day is more of a presentation/display issue and should be done on the front end for maximum maintainability and flexibility, not in the scheduler, whose responsibility is implementing the scheduling algorithm
> * Working with strings like "Tuesday" is error-prone and less flexible than working with the actual `Date()`s or numbers of days
> 
> I suggest this logic gets worked into the front end, perhaps making use of the `TaskFilter` module.

ok so here are some comments that might resolve your doubts:
1. Nope its not rigid, if you want to view the next week or may be not 7 days but more than i will query with a startDate and endDate accordingly. i will fetch the next week to show the desired days or week.

2 & 3 no i m not bounding you to work on that day name like "Tuesday", you can put date too. rust can't extract the day name from date string/object ? I agree the taskFilter can be used, i m putting it as our last option but i recommend that we get output from scheduler in a structured format display above so we are just good to go. adding helper in between is a dependency which is not good for coming features as it will increase one layer of computation between and input and output.

lemme know if its still not possible then we will move forward with taskFilter function u made.

**Comment by egithinji** [comment]
Please see this latest commit where I've implemented filtering on the front end.

I've added a dropdown to demonstrate how one can easily change the number of days to display and the app reactively displays the correct number of days.

Some of the styling (like the color lines) will need to be moved to the MyTimeline component and I haven't done that yet, but this should be sufficient to demonstrate the advantage of this approach.

**Comment by Tushar-4781** [comment]
i don't know how to respond lol, @egithinji i didn't ask a proof, I understood your function at first place. I asked you whether its  possible for you to make the desired output at backend itself. I already mentioned that if its not possible then definitely we are gonna be using the helper function you created, I think you misunderstood.

**Comment by tijlleenders** [comment]
@egithinji So looks like you have this, nice work.

Can you remove the dropdown and restore the page formatting to 'normal' so we can get this merged?

**Comment by egithinji** [comment]
Please see #937

**Comment by Tushar-4781** [comment]
@egithinji can we close this ?

**Comment by egithinji** [comment]
@Tushar-4781 Yes

**Pull request closed without merging**
