### PR TITLE
playwright test for collaboration feature

### LINKED ISSUE #1678: Write tests for collaboration feature
**Is your feature request related to a problem? Please describe.**
Ex. It's not possible to review collaboration features and its cases manually in PRs

**Describe the solution you'd like**
Write tests for collaboration feature.

**Additional context**
Create 3 users. one as sharer and 2 as collaborator check if sharing between all three works smoothly. create test cases for example like A shares with B where C is receiving when B accepts those changes. check that C is receiving only the changes he should be receiving. consider such scenarios and write tests

### LINKED ISSUE #1748: Fix CI test failing
**Describe the bug**
Changes in sharing flow make the CI test fail.

**To Reproduce**
See CI logs.

**Expected behavior**
Test should be updated so it doesn't fail.

**Additional context**
Test failure introduced in PR #1740 
@vinaybadgujar102  My bad - I didn't notice this.

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #1678 
Resolves #1748 

#### 1. Establishing Sharing Relationships
The testing process emphasizes the sharing aspect of the feature, where users invite each other to establish a sharing relationship.

- **User A and User B**:
  - User A creates a contact named B and shares an invitation link with B.
  - User B uses the link provided by A and accepts the sharing relationship by naming A.

- **User B and User C**:
  - User B repeats the process, creating a contact named C and inviting C into a sharing relationship.
  - User C uses the link provided by B and accepts the sharing relationship by naming B.

#### 2. Sharing Goals and Upgrading to 'My Goals'
After the sharing relationships are established, users proceed to share goals and decide to upgrade the received goal. This enables them to suggest edits to shared goals and also places shared goals in the "My Goals" section.

- **Goal Sharing by User A**: 
  - User A shares a goal with User B, which appears in User B's 'Partner' section.

- **Upgrading to 'My Goals' by User B**: 
  - User B decides to collaborate on the received goal. This action moves the goal to User B's 'My Goals' section, changing its engagement level.

- **Goal Sharing by User B**: 
  - User B shares the same goal with User C, appearing in User C's 'Partner' section.

- **Upgrading to 'My Goals' by User C**: 
  - User C similarly upgrades the goal to their 'My Goals' section.

#### 3. Suggesting Edits and Sharing Changes
Once goals are shared and possibly upgraded to collaboration, users suggest edits and share changes.

- **Edit by User A**: User A edits the goal and submits the changes. The test checks if User B receives these changes as expected. Once User B accepts the changes, the test further verifies that User C receives the update.

- **Edit by User B**: User B then edits the goal. The test verifies that both User A and User C receive the updates correctly.

- **Edit by User C**: User C makes changes to the goal. The test ensures that User B receives these edits. Once User B accepts the changes, the test further verifies that User A receives the update.

### CODE REVIEW

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Can you update/improve the testing flow description?  
We should avoid the word collaboration in principle. The main interaction mode between players is sharing. I share my changes with you - and you suggest changes to my goal (in partner mode) or share your changes on your goal (when goal is in your goals).  

>A collaboration connection is initiated between User A (the sharer) and User B (the first collaborator).  

You can't initiate a collaboration directly.  
What you can do is invite another user to establish a sharing relationship.  
This is not a one-step process and first has to be broken down into:  
- User A creates contact named B
- User A invites B into a sharing relationship using a link
- User B clicks the link and accepts sharing relationship by naming A

Now... a 'collaboration' is possible.
- User B can decide to upgrade the received goal to a collaboration.  
This will place it in User B My goals instead of User B partner

So the only difference between a shared goal and a collaboration is where it is seen on the UI from B's perspective.  
It is a one-sided choice - which is counter-intuitive for most people. I don't think we have implemented anything to signal to user A whether user B has upgraded the goal shared with him/her to a collaboration - but that could be interesting.

**Comment by vinaybadgujar102** [comment]
@tijlleenders, I have updated the PR description. Please review if the required test scenarios are covered.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Yes this looks right.  

Great work and happy this test will pass once merged!

There is also a need for testing the 'suggestion' feature, without ipgrading to collaboration. Can you make a separate issue+test for that?

**Review by tijlleenders — DISMISSED** [review]

**Comment by vinaybadgujar102** [comment]
@Tushar-4781, fixed the width problem

**Review by Tushar-4781 — APPROVED** [review]

**Pull request merged**
