### PR TITLE
regularly show scheduler error modal and handle cached schedule storage on scheduler crash 

### LINKED ISSUE #1917: Catch scheduler error
**Is your feature request related to a problem? Please describe.**
It's very annoying when you can't use Goals/Feelings when there is an error calculating the schedule. Now whenever there is an error on mobile the whole app becomes unusable with only a white screen.

**Describe the solution you'd like**
1. Catch and show the scheduler error in a modal.
2. Don't update the cached version - so show the previous (working) output of the scheduler after closing the modal.

**Describe alternatives you've considered**
None.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #1917

### CODE REVIEW

**Comment by tijlleenders** [comment]
@vinaybadgujar102 No, this is not showing the error still. Thanks for trying. 
Let's just park the issue and move on.

**Comment by vinaybadgujar102** [comment]
@tijlleenders This PR addresses the issue where the error is only logged once when the scheduler fails. Previously, when the scheduler errored, the cached schedule was stored as undefined in the database. This undefined response caused further issues downstream. Additionally, since the input remained the same, the scheduler wouldn't run again, leaving the error unlogged. This PR resolves these issues.

**Review by tijlleenders — APPROVED** [review]
Ah OK, well that indeed works.
@Tushar-4781  Good to merge?

**Comment by Tushar-4781** [comment]
@vinaybadgujar102 could you please share a test or step to verify the work and o/p of this mechanism ?

**Comment by vinaybadgujar102** [comment]
@Tushar-4781, Steps to break the scheduler:
1. Reschedule any task to 7 days.
2. Change the system's date to 2 days ahead.
3. This breaks the scheduler and shows an error as a modal on the My Time page.

>This PR addresses the issue where the scheduler error is only logged once when the scheduler fails. Previously, when the scheduler errored, the cached schedule was stored as undefined in the database. This undefined response caused further issues downstream. Additionally, since the input remained the same, the scheduler wouldn't run again, leaving the error unlogged. This PR resolves these issues.

**Comment by tijlleenders** [comment]
I tested manually and can confirm a breaking scheduler shows an error message every time you visit the My time page, instead of once on app startup only.  

Don't think it's worth the effort to make an automated test for this - as it seems tricky to realize...  

When this PR merges - we'll need a separate issue on the backlog (low prio) for showing better error messages (like in the console).

**Pull request merged**
