### PR TITLE
#1822 fix some alignments

### LINKED ISSUE #1822: Align Goal circles to logo
**Is your feature request related to a problem? Please describe.**
It's very annoying when things are not aligned.

**Describe the solution you'd like**
Align Goal circles to the logo.

**Describe alternatives you've considered**
None.

**Additional context**

### PR DESCRIPTION
**Pull request by DevDaniloFerrari**
Resolves #1822 
We can still improve some alignments, removing percentages and treating them better with flexbox.
But the alignment has already been improved.

image
image

### CODE REVIEW

**Comment by DevDaniloFerrari** [comment]
@tijlleenders well observed, done!

**Comment by DevDaniloFerrari** [comment]
@tijlleenders I already made the changes, do you want any other changes?

**Comment by tijlleenders** [comment]
@DevDaniloFerrari Yeah I didn't know if you were ready for a next review yet - so I marked the PR as draft. I can still move the goals slightly left - even if I can't move them off-screen:

image

**Review by tijlleenders — APPROVED** [review]
Great stuff @DevDaniloFerrari 

Please be patient for the code review by @Tushar-4781 - then we'll merge.

**Review by Tushar-4781 — APPROVED** [review]

**Pull request merged**
