### PR TITLE
Language Tag Visible while adding/updating goal

### LINKED ISSUE #227: Language tag when adding goal
When adding a goal on AddGoal page, the language tag should appear below the title. 

For example, if the user interface is in English, the tag "English" should appear next to the other possible tags like "1h" and "daily".

### PR DESCRIPTION
**Pull request by Tushar-4781**
Resolves #227

### CODE REVIEW

**Review by tijlleenders — CHANGES_REQUESTED** [review]
The default goals are English as expected.
However if one chooses a different language at the beginning ie Hindi, I'd expect that language to show - and being saved - not English.

**Comment by tijlleenders** [comment]
When I make a Goal in French mode, the French Goal has the right tag:


... but when I edit it again it has the wrong tag:

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Editing a saved non-English Goal shows the wrong tag.

**Comment by Tushar-4781** [comment]
Sorry @tijlleenders actually the commit is taking time. I think husky is checking or something idk. Will mark this pr draft. Will change it for review as soon as its pushed.

**Review by tijlleenders — APPROVED** [review]

**Pull request merged**
