### PR TITLE
Add the new toggle button

### PR DESCRIPTION
**Pull request by mallikarai05**

### CODE REVIEW

**Review by Tushar-4781 — COMMENTED** [review]
which issue does this PR resolve?

**Comment by mallikarai05** [comment]
@Tushar-4781 this is a new thing, I'll make an issue explaining the details.

**Comment by mallikarai05** [comment]
It's issue #867

**Comment by tijlleenders** [comment]
@Tushar-4781 Good point!

I just added #867 for this.

**This PR will not be merged now** - it's just to park the proposal Mallika made.
Implementation will have to be done by you once you have time to discuss and we all agree on the way forward.

**Comment by Tushar-4781** [comment]
Implemented in #972

**Pull request closed without merging**
