### PR TITLE
Renamed the Share 1:1 into Share privately

### LINKED ISSUE #1469: Rename share 1:1
**Is your feature request related to a problem? Please describe.**
It's very nice when wording is clear.

**Describe the solution you'd like**
Rename 'Share 1:1' to 'Share privately'.

**Describe alternatives you've considered**
Keeping it the way it is. 1:1 is confusing for some people.

**Additional context**

### PR DESCRIPTION
**Pull request by Hari-Bombon**
I have renamed  Share1:1 to Share privately in the Share goals  #1469 

Resolves #1469

### CODE REVIEW

**Comment by tijlleenders** [comment]
That's very nice @Hari-Bombon - thanks!  
I've added 'Resolves #1474' to the PR description so the issue will be auto-closed when the PR merges.  

I see some formatting changes which make it hard to merge this right away. @Tushar-4781 Can you take a look?
  

Feel free to work on anything ales @Hari-Bombon - just ask to be assigned the issue just to make sure there's no conflicts - and to check if the issue is still relevant/worth solving... we sometimes get a little outdated in the issue list ;)

**Comment by Hari-Bombon** [comment]
@tijlleenders Thanks !!! Feel free to assign me to any other tasks or issues, and I'll be happy to help. Let's keep the collaboration going!

**Review by Tushar-4781 — APPROVED** [review]
LGTM 
Welcome @Hari-Bombon , i would like to know why the reformatting in the imports?

**Comment by Tushar-4781** [comment]
welcome @Hari-Bombon , i would like to know why the reformatting in the imports?

**Review by Tushar-4781 — CHANGES_REQUESTED** [review]
Can you please make the imports back to Pascal's triangle style its much organized
image

**Comment by Hari-Bombon** [comment]
@Tushar-4781 Check it out now

**Review by Tushar-4781 — APPROVED** [review]

**Pull request merged**
