### PR TITLE
refactor: introducing generic Custom ZModal for reduced redundancy and enhanced maintainability

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
This pull request introduces the `ZModal` component, which abstracts common props used in our existing antd modal.

- **Common Property Abstraction**: Centralizes shared modal properties to reduce redundancy.

- **Type-Based Customization**: Utilizes a `type` prop for applying distinct styles (can also be used for distinct behaviour), enhancing code clarity.

- **Easy Maintainability**: Simplifies updates and modifications to modal behaviour and appearance, ensuring changes are centralized and consistent.

### CODE REVIEW

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Great initiative.  
Please do make an issue first and discuss these kinds of decisions with @Tushar-4781 before you start implementing.  
Pausing and getting validation on the direction before writing code is a good thing.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Can you provide a link to the docs/GH of the ZModal component?

**Comment by vinaybadgujar102** [comment]
The ZModal is actually a custom wrapper created around the antd Modal component. Internally it uses antd's modal only. It just centralizes common props which we used in our existing modal. 

The idea to build this component appeared while solving #1612 where maskStyle prop had to be added to every file where the modal was used. With this new ZModal. we only have to do changes in one file when dealing with modals.

The name ZModal is used based on the existing ZAccordian component in src/common folder.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Thanks for explaining. So custom wrapper - as in made by us?

**Comment by vinaybadgujar102** [comment]
@tijlleenders yes

**Review by Tushar-4781 — APPROVED** [review]
Great, @vinaybadgujar102 , this matter has been pending for quite some time in my mind.

**Pull request merged**
