### PR TITLE
Update: Show drop down icon to close task card 

### LINKED ISSUE #994: Whole MyTime card should respond to tap and collapse again if tapped 2nd time
The tap are of cards on MyTime should be like so:

In first tap - buttons forget / reschedule / done should show.

If tapped again (not on buttons) card should collapse again.

### PR DESCRIPTION
**Pull request by Tushar-4781**
Resolves #994

### CODE REVIEW

**Comment by tijlleenders** [comment]
@Tushar-4781 I like the dropdown but still woild like the whole card to be tappable to expand.

**Comment by Tushar-4781** [comment]
Oh ok lemme do that

**Comment by tijlleenders** [comment]
@Tushar-4781 Sweet that's what I meant.
Can you also make it work for collapse?

**Review by tijlleenders — APPROVED** [review]
Great!

**Pull request merged**
