### PR TITLE
Enable clicks on entire title area for suggestions

### LINKED ISSUE #1930: Autocomplete title based on Archive goals
**Is your feature request related to a problem? Please describe.**
It's very annoying when you have lots of (recurring)  shopping list items in archive - and you have to search for it manually, not sure if it was already in the archive. If you don't check - you have to type more and also get duplicates.

**Describe the solution you'd like**
While typing a goal/budget title, search the archive for the first archived goal/budget with the same starting characters.
If found, show the rest of the text from the archive to the right of the cursor, in a lighter/placeholder color.
When tapping to the right of the cursor on the autosuggestion, remove the goal/budget from archive and complete all element (title/options) in the modal based in the archive.

**Describe alternatives you've considered**
Show a list when multiple matches. Confusing and more complicated. Just show the first match.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #1930

### CODE REVIEW

**Review by tijlleenders — APPROVED** [review]
Yes, this fixes the issue of the precision click.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 I think there are some other commits mixed in with this PR?

**Comment by vinaybadgujar102** [comment]
They are just small improvements

**Review by Tushar-4781 — APPROVED** [review]
thanks for taking care of this :)

**Pull request merged**
