### PR TITLE
fix: ensure confirmation state persists across sessions

### LINKED ISSUE #1925: Don't ask again pref not stored
**Describe the bug**
When I delete something on GrapheneOS/Vanadium the don't ask again is not persisted over a reatart of the app.

**To Reproduce**

1. Make a goal
2. Delete the goal
3. Tick don't ask again
4. Restart the app
5. Try 1+2 again

**Expected behavior**
Remember prefs past a restarts.

**Screenshots**
None. 

**Additional context**
None.

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #1925 
The bug occurred due to mistyping the localStorage key name "confirmationState" as "confirmationService". To prevent similar issues in the future, I created an enum that maps localStorage keys to ensure type safety.

### CODE REVIEW

**Review by tijlleenders — DISMISSED** [review]
Agree @Tushar-4781 ?

**Comment by tijlleenders** [comment]
@vinaybadgujar102 The playwrigt test failing is the 'flaky' test again?

**Comment by vinaybadgujar102** [comment]
Yeah the collaboration one

**Comment by tijlleenders** [comment]
> Agree @Tushar-4781 ?

*bump*

**Review by Tushar-4781 — APPROVED** [review]

**Comment by vinaybadgujar102** [comment]
@Tushar-4781 fixed merge conflict.

**Comment by tijlleenders** [comment]
@Tushar-4781 *bump*

**Review by Tushar-4781 — APPROVED** [review]

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Can you resolve the merge conflicts?

**Comment by vinaybadgujar102** [comment]
> @vinaybadgujar102 Can you resolve the merge conflicts?

Done

**Review by tijlleenders — APPROVED** [review]

**Pull request merged**
