### PR TITLE
577 move update goal button

### PR DESCRIPTION
**Pull request by GithinjiHans**

### CODE REVIEW

**Comment by tijlleenders** [comment]
@GithinjiHans Can you mark this PR as draft until you ask for a review? 

Otherwise it is not clear if it is ready for review or not.

**Review by GithinjiHans — COMMENTED** [review]
This solved the bug in the PR

**Review by Tushar-4781 — CHANGES_REQUESTED** [review]
I can't see the Update Goal title & helper text completely on the update Goal page

**Comment by GithinjiHans** [comment]
> I can't see the Update Goal title & helper text completely on the update Goal page

I removed them because Issue #577 stated that it's repetitive

**Review by tijlleenders — CHANGES_REQUESTED** [review]
image

Two things, 
1. In non-mobile mode the button is not aligned.
2. Text can be removed (it is already in the input box when adding a new task)

**Pull request closed without merging**
