### PR TITLE
Made the download repo shell script.

### PR DESCRIPTION
**Pull request by GithinjiHans**
To run it on terminal type ./downloadRepo.sh

### CODE REVIEW

**Comment by GithinjiHans** [comment]
I haven't tested it on windows...anyone using windows test it and give me your feedback

**Review by pulkitvyas08 — CHANGES_REQUESTED** [review]
Doesn't work on windows. There's no `~/` in Windows

**Comment by tijlleenders** [comment]
I don't understand what issue this PR closes.
If it's just a one-line shell script I don't think it adds anything.

**Comment by GithinjiHans** [comment]
It closes issue #321 but we can use a button and this link https://github.com/tijlleenders/ZinZen.git in the UI for the download repo function but issue #321 says that it should run in console so a shell script is the best solution.

**Comment by tijlleenders** [comment]
Deleting this PR as it was based on a misinterpretation of the issue #321

**Comment by tijlleenders** [comment]
> It closes issue #321 but we can use a button and this link https://github.com/tijlleenders/ZinZen.git in the UI for the download repo function but issue #321 says that it should run in console so a shell script is the best solution.

Sorry, I meant the javascript web developer console.

**Pull request closed without merging**
