### PR TITLE
first release of scheduler wasm

### PR DESCRIPTION
**Pull request by tijlleenders**
You can use the following code to call the scheduler from any React page:
```
import init from  "../../../pkg/scheduler";
import { schedule } from "../../../pkg/scheduler.js";

<Button onClick={ () =>           
            (async function () {
                scheduler = await init();
                console.log(scheduler);
                console.log(schedule({
                  "startDate": "2022-01-01",
                  "endDate": "2022-01-02",
                  "goals": [
                    {
                      "id": 1,
                      "title": "shopping",
                      "duration": 1,
                      "start": "2022-01-01T10:00:00",
                      "deadline": "2022-01-01T13:00:00",
                    },
                    {
                      "id": 2,
                      "title": "dentist",
                      "duration": 1,
                      "start": "2022-01-01T10:00:00",
                      "deadline": "2022-01-01T11:00:00",
                    },
                    {
                      "id": 3,
                      "title": "exercise",
                      "duration": 1,
                      "start": "2022-01-01T10:00:00",
                      "deadline": "2022-01-01T18:00:00",
                    },
                  ],
                }))
            })()}>
            click me
          </Button>
```

### CODE REVIEW

**Review by Tushar-4781 — COMMENTED** [review]
@tijlleenders do you want me to fix the ESlint tc or shall we get it merge

**Comment by tijlleenders** [comment]
> @tijlleenders do you want me to fix the ESlint tc or shall we get it merge

Please fix.
Also, didn't we have a pre-commit hook to avoid me pushing ESLint errors to the public?

**Comment by Tushar-4781** [comment]
@pulkitvyas08 any thoughts why @tijlleenders is able to push ?

**Comment by tijlleenders** [comment]
@Tushar-4781 Can you fix the errors and merge?
@pulkitvyas08 Won't be available for some time so let's not let this PR hang because of the ESLint error detection not working.

**Review by Tushar-4781 — APPROVED** [review]

**Pull request merged**
