### PR TITLE
sorting subgoal fix

### LINKED ISSUE #1988: Sorting subgoal errors out the app
[Screencast from 26-07-24 08:07:06 PM IST.webm](https://github.com/user-attachments/assets/b2f13aa6-a707-4e5d-8b35-0b92019ecfcf)

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #1988

### CODE REVIEW

**Review by tijlleenders — APPROVED** [review]
Yeah this looks good.  

@Tushar-4781 Happy with the code?

**Review by tijlleenders — APPROVED** [review]
Yeah this works.

@Tushar-4781 Happy with the code?

**Review by Tushar-4781 — COMMENTED** [review]
@vinaybadgujar102 what's the exact technical issue here? the sorting is working fine at root level but at subgoals level its not. can you comment on this because i don't want to introduce any additional states and useEffect hooks to manage these states

**Comment by vinaybadgujar102** [comment]
@Tushar-4781, I refactored the code and removed the unnecessary state. The issue was in the GoalList component of subGoals. In the setGoal function, the handleDragEnd function was being passed as an argument instead of the GoalItem array.

**Pull request merged**
