### PR TITLE
add translation to hebrew

### PR DESCRIPTION
**Pull request by HadassaAvimor**
I added a Hebrew translation option.
It is important that Hebrew speakers can also enjoy the application.

### CODE REVIEW

**Review by tijlleenders — CHANGES_REQUESTED** [review]
Thank you so much @HadassaAvimor !

That is great! More languages is better. We just haven't implemented auto translation (yet) for sharing Goals between languages.

Sorry for the delay in response - I had a crazy busy week.  

Anyway there are a few small tweaks - if you can:
- Capitalize the h in hebrew on selection menu
image

- Some Tasks calculated by the scheduler for the default Goals are not showing in Hebrew.
image

- The default Goals are not translated somehow.
image

- The sub menu of Goals for Goals containing a budget (like Daily habits) still shows 'budget'
image


I'll post pictures shortly - on a phone right now for which I'm still figuring out how to set app permissions correctly...

**Comment by tijlleenders** [comment]
@vinaybadgujar102  Maybe you can help bring this PR in? It requires a bit more understanding of the translation and app code. 

Let @HadassaAvimor know if you start working on it.

**Comment by HadassaAvimor** [comment]
@tijlleenders ,
Apologies for my late response; I've also had a really busy week! I've actually started working on it and have corrected everything except for the fourth section. I'm committing those changes now, and I’d appreciate an update on whether @vinaybadgujar102  will continue from here or if I should revisit it when I have more time.
Thanks!

**Comment by tijlleenders** [comment]
> @tijlleenders , Apologies for my late response; I've also had a really busy week! I've actually started working on it and have corrected everything except for the fourth section. 

@HadassaAvimor Oh, my apologies too for assuming you had blocked on the work - not on the time. Please do continue and take your time. No rush. We can let this one hang for a few weeks as long as we know you're trying to find the time for it.

@vinaybadgujar102 will stand-by for if you have any questions.

**Comment by tijlleenders** [comment]
@HadassaAvimor I'll put an issue on the backlog for finishing up the last 5%.

**Comment by vinaybadgujar102** [comment]
@tijlleenders I think we can merge this

**Review by tijlleenders — APPROVED** [review]

**Pull request merged**
