### PR TITLE
added Pull Request from fork actions triggers

### PR DESCRIPTION
**Pull request by tijlleenders**
As can be seen in PR #311 the GitHub Actions don't get triggered.
This is because the PR comes from a forked repo  
  => not pushing to the ZinZen repo  
  => not triggering 'push' event on ZinZen repo
  => not triggering GitHub Actions.

I added a trigger for pull_request: [opened, edited, ready_for_review]

### CODE REVIEW

**Comment by tijlleenders** [comment]
Hmm even for this PR, only 1 check is running...
@pulkitvyas08 thoughts?

**Comment by tijlleenders** [comment]
I see some errors in the Actions. Let met fix...

**Comment by tijlleenders** [comment]
Need a fix so that Actions only run once if triggered by multiple events:
image

Adding this line as a condition to the job does just that:
```
if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
```
The job will still try to run twice - but the if will abort one of them before running.  
Found the solution on [this page](https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/)

We'll have to merge the code first to double-check it also has the required behavior for PRs from forked repos.

**Comment by tijlleenders** [comment]
Hmmm... it's still running twice.
Will have to do some more research.

**Comment by tijlleenders** [comment]
So the first time I changed the workflow the actions got run twice in the PR overview...

But now it's OK:
image


Confirmed they run only once in the Actions overview:
image

**Comment by tijlleenders** [comment]
Ah...
I understand now - it's not that they're running twice on a single commit.  
It's just that they run:
- once when I commit to the PR
- then also once when I set the PR from draft to final status.
The PR UI then shows 7 checks.

So the confusion is cleared up!

**Review by pulkitvyas08 — APPROVED** [review]

**Pull request merged**
