### PR TITLE
mytimeline refactor

### LINKED ISSUE #1773: Refactor: Break `MyTimeline` component  into Smaller Components #1762
Describe the problem
The MyTimeline component is currently a single, large entity, making maintenance and refactoring challenging.

Expected solution
Decompose the MyTimeline component into smaller, modular components to improve maintainability and development efficiency.

### LINKED ISSUE #1814: Make vertical timeline less busy
**Is your feature request related to a problem? Please describe.**
It's very annoying when things are very busy.

**Describe the solution you'd like**
Make the timeline a bit thinner.
Connect all the different parts so it turns into one continuous line, just like the horizontal one.

**Describe alternatives you've considered**
None.

**Additional context**
Current (Disco-lights busy) status:
image

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #1773
resolves #1814

### CODE REVIEW

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Is 'classnames' really necessary and widely used/revognized amongst react programmers?  

It requires learning additional syntax - that even if not conplicated makes it harder to read/edit?
 
Is this utility dev 'sugar' only or does it also impact build size?

**Review by tijlleenders — APPROVED** [review]
Yeah, this looks good.  
Is it possible to round the angles a little bit, like on the horizontal bar?   

There are more changes to come (separate issues) but this lays a good foundation.

**Review by Tushar-4781 — CHANGES_REQUESTED** [review]
We can't justify creating multiple files for such a small component. To split the code of any file, it should have at least 250 lines of code.

**Comment by vinaybadgujar102** [comment]
@Tushar-4781, In #1999, we're adding 'Reminders' to the timeline, which comes with its own logic. This will make the current timeline component larger and harder to manage. By breaking the component into smaller parts, it'll be easier to handle these new changes and keep the code more organized.

**Comment by Tushar-4781** [comment]
@vinaybadgujar102 in that case you can continue that in the same PR.

**Comment by vinaybadgujar102** [comment]
Closed the PR in favor of a better implementation in #2092

**Pull request closed without merging**
