### PR TITLE
show hints in accordian

### LINKED ISSUE #1823: Store and show Hints
**Is your feature request related to a problem? Please describe.**
It's very annoying when you call the Hints API but do nothing with the result.  
#1739 enabled getting the Hints, now we need to store and show them.

**Describe the solution you'd like**
Store all retrieved hints in a collection - and show them on the appropriate goals, just like the 'Done' drawer, but then a separate 'Hints' drawer below it.  
When clicking the Goal circle for each Hint you will have three options:  
- Accept hint
- Delete hint
- Report hint

**Describe alternatives you've considered**
None.

**Additional context**
There is still no mechanism to check for new Hints on a schedule.  
This will be implemented by a separate issue. For now, if you want to see if there are new Hints (call the fetch Hint API) - you'll need to edit the Goal for which you want Hints. In the future, there will be two triggers for calling the Hints API:  
- When creating/editing a Goal with Hints enabled
- On the Hint schedule   

The Hint schedule will have some business logic to check more frequently in the beginning - then exponentially back off if there are no new Hints found.

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #1823

### CODE REVIEW

**Comment by vinaybadgujar102** [comment]
Remaining Tasks:

- [ ] Report Hint button functionality
- [ ] When a user deletes a particular hint, the same hint should not be recommended again

**Comment by vinaybadgujar102** [comment]
@tijlleenders what should the report hint button do? Also suggest an icon for the report hint button

**Review by tijlleenders — DISMISSED** [review]
This is AWESOME!!!

There's many follow-up issues we can make 
... but this is a killer feature!

**Comment by tijlleenders** [comment]
@Tushar-4781 Code ok?

**Comment by tijlleenders** [comment]
> Remaining Tasks:
> 
> - [ ] Report Hint button functionality
> - [ ] When a user deletes a particular hint, the same hint should not be recommended again.( In this pull request, it's a bit complicated for me. It can be handled as a separate issue. )

@vinaybadgujar102 You can make new issues for this. The report feature will need a backend API - but you can use the feedback API for now.

**Comment by vinaybadgujar102** [comment]
@vinaybadgujar102 I can't get my Goals to the impossible state after the last commit.

@tijlleenders, i think you commented on wrong PR

**Comment by tijlleenders** [comment]
Yup @vinaybadgujar102

I was confused.

**Review by tijlleenders — CHANGES_REQUESTED** [review]
When a Goal 'Learn Rust' is made without hints enabled. Then you edit again and enable hints... it doesn't close the modal on pressing 'Update'.

**Comment by tijlleenders** [comment]
> @Tushar-4781 Code ok?

@Tushar-4781 *bump*

**Review by tijlleenders — APPROVED** [review]

**Pull request merged**
