### PR TITLE
fixes #1382

### LINKED ISSUE #1382: Add paper crumble sound when deleting Goal
**Is your feature request related to a problem? Please describe.**
It's very nice when you get auditory feedback on actions.

**Describe the solution you'd like**
Play sound of a paper crumbling when deleting a Goal. Sound should be public domain license.

### PR DESCRIPTION
**Pull request by Shahzaib-Iqbal-1057**
Hey! I have added the goal deleting sound. I'll let you be the judge and decide if the sound is good enough or not. Thanks!

### CODE REVIEW

**Comment by tijlleenders** [comment]
@Shahzaib-Iqbal-1057 Yeah I like! 
Thanks 🙏 

Could you include the reference of where you found it so we know the license is public domain?  
Do you need help resolving the merge conflicts?

**Comment by tijlleenders** [comment]
@Shahzaib-Iqbal-1057 
I see you have continued on the previous PR branch (I see superscript commits).  
It helps to make a new branch of the main branch for every issue / PR. That way your change for the superscript is not 'mixed in' with this change.  
If not - consider the situation where there is a problem or discussion on one of the issues/PRs ; then _both_ can't be merged.  
Also, it makes it harder to review as changes not related to the issue are mixed in.  

For this PR it is very obvious - so no worries - but more complicated issues it will quickly get a little messy.

**Comment by Shahzaib-Iqbal-1057** [comment]
Hey! Really sorry for this. I had created another branch before but I ended up pushing the commit to the previous one. Also, don't worry I'll resolve the merge conflicts by myself. As for the sound effect, I got it for free from this website : 
website link : https://pixabay.com/sound-effects/search/crumpling%20paper/
The sound effect I downloaded is "Crumple-03". Here is the link to their license agreement :
License Agreement : https://pixabay.com/service/license-summary/

**Comment by tijlleenders** [comment]
@Shahzaib-Iqbal-1057 That's perfect - we can use this.

**Comment by tijlleenders** [comment]
Superceded by #1387

**Pull request closed without merging**
